<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="MSTest" Version="4.3.3" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="MySqlConnector" Version="2.6.2" />
    <PackageVersion Include="Selenium.WebDriver" Version="4.47.0" />
    <PackageVersion Include="Selenium.WebDriver.GeckoDriver" Version="0.37.1" />
    <PackageVersion Include="Selenium.WebDriver.MSEdgeDriver" Version="151.0.4129.59" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="10.0.11" />
    <PackageVersion Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
  </ItemGroup>
</Project>