<Project>
	<PropertyGroup>
		<UpDir>..</UpDir>
		<BaseOutputPath>$(UpDir)\..\bin\$(MSBuildProjectName)\</BaseOutputPath>
		<BaseIntermediateOutputPath>$(UpDir)\..\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<DefineConstants>NULLABLE</DefineConstants>
		<ImplicitUsings>disable</ImplicitUsings>
		<Company>JC-Soft</Company>
		<Authors>Joe Care</Authors>
		<Copyright>Copyright © JC-Soft 2026</Copyright>
		<GenFreeWinPath>..\..\GenFreeWin\</GenFreeWinPath>
		<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
		<SuppressTfmSupportBuildErrors>true</SuppressTfmSupportBuildErrors>
		<_WinAhnenGenFreeWinInfoPath>$(MSBuildThisFileDirectory)..\Gen_FreeWin\.info.md</_WinAhnenGenFreeWinInfoPath>
		<_WinAhnenGenFreeWinInfoExists Condition="$([System.IO.File]::Exists('$(_WinAhnenGenFreeWinInfoPath)'))">true</_WinAhnenGenFreeWinInfoExists>
		<_WinAhnenGenFreeWinInfoExists Condition="'$(_WinAhnenGenFreeWinInfoExists)'==''">false</_WinAhnenGenFreeWinInfoExists>
	</PropertyGroup>
	<PropertyGroup Condition="$(_WinAhnenGenFreeWinInfoExists) == 'true'">
		<GenFreeWinPath>..\..\Gen_FreeWin\</GenFreeWinPath>
	</PropertyGroup>

	<Target Name="PrintWinAhnenProps" BeforeTargets="Build">
		<Message Text="WinAhnen.props: GenFreeWinPath=$(GenFreeWinPath)" Importance="high" />
	</Target>
</Project>
