0: Name:
0: Ref:
2: <A NAME="I12">
4: </A>
3: Johannes  Vieser 
0: info:
3: BERUF
0: data:
4: </EM>
3: : Landwirt, Fabrikarbeiter
0: info:
3: GEBURT
0: data:
4: </EM>
3: : 16 May 1800, Lahr, Baden, Germany\n
3: TAUFE
0: data:
4: </EM>
3: : 18 May 1800, Lahr, Baden, Germany\n
3: TOD
0: data:
4: </EM>
3: : 27 Jan 1871, Lahr, Baden, Germany\n
3: BEGRÄBNIS
0: data:
4: </EM>
3: : 30 Jan 1871, Lahr, Baden, Germany\n
3: VERWEIS
0: data:
4: </EM>
3: : Ic,30,VIIg\n
0: Eltern:
3: Vater: 
0: Ref:
2: <A HREF="../d0002/I14.html">
3: Johannes  Vieser 
0: Eltern:
3: Mutter: 
0: Ref:
2: <A HREF="../d0003/I15.html">
3: Anna Christina  Binz 
0: Familie:
3: Familie 1
0: Partner:
0: Ref:
2: <A HREF="../d0001/I13.html">
3: Elisabeth  Schmidt 
0: info:
3: HEIRAT
0: data:
4: </EM>
3: :  5 Nov 1827, Lahr, Baden, Germany\n
0: Kind:
0: Ref:
2: <A HREF="../d0011/I10.html">
3: Johann Christian  Vieser 
0: Kind:
0: Ref:
2: <A HREF="../d0011/I386.html">
3: Elisabeth  Vieser 
0: Kind:
0: Ref:
2: <A HREF="../d0012/I387.html">
3: Elisabeth  Vieser 
0: Kind:
0: Ref:
2: <A HREF="I388.html">
3: Sophia Magdalena  Vieser 
0: Kind:
0: Ref:
2: <A HREF="../d0001/I389.html">
3: Karolina Magdalena  Vieser 
0: Kind:
0: Ref:
2: <A HREF="../d0007/I390.html">
3: Johann Georg  Vieser 
