0: Name:
0: Ref:
2: <A NAME="I5">
4: </A>
3: Friedrich Wilhelm  Vieser 
0: info:
3: BERUF
0: data:
4: </EM>
3: : Wagnermeister
0: info:
3: GEBURT
0: data:
4: </EM>
3: :  4 Jan 1901, Lahr, Baden, Germany\n
3: TAUFE
0: data:
4: </EM>
3: : 10 Feb 1901, Lahr, Baden, Germany\n
3: TOD
0: data:
4: </EM>
3: : 27 Oct 1980, Lahr, Baden, Germany\n
3: VERWEIS
0: data:
4: </EM>
3: : Ic,64,Xc\n
0: Eltern:
3: Vater: 
0: Ref:
2: <A HREF="../d0003/I8.html">
3: Friedrich  Vieser 
0: Eltern:
3: Mutter: 
0: Ref:
2: <A HREF="../d0004/I9.html">
3: Wilhelmine  Gässler 
0: Familie:
3: Familie 1
0: Partner:
0: Ref:
2: <A HREF="../d0001/I6.html">
3: Elfriede  Siehl 
0: Kind:
0: Ref:
2: <A HREF="../d0009/I1.html">
3: Hans Friedrich  Vieser 
0: Kind:
0: Ref:
2: <A HREF="../d0002/I7.html">
3: Gerhard Fritz  Vieser 
