# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/CSharpBible" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/TestStatements" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/JC-AMS" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/Transpiler_pp" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/GenFreeWin" # Location of package manifests
    schedule:
      interval: "weekly"
