<Project>
  <PropertyGroup>
    <AssemblyName>Polyline</AssemblyName>
    <IntermediateOutputPath>..\..\..\obj\Polyline\Debug\</IntermediateOutputPath>
    <BaseIntermediateOutputPath>..\..\..\obj\Polyline\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>C:\Projekte\CSharp\CSharpBible\Graphics\Polyline\..\..\..\obj\Polyline\</MSBuildProjectExtensionsPath>
    <_TargetAssemblyProjectName>Polyline</_TargetAssemblyProjectName>
    <RootNamespace>Polyline</RootNamespace>
  </PropertyGroup>
  <Import Project="..\Graphics.props" />
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net462;net472;net48;net481</TargetFrameworks>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.props" />
  <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.targets" />
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="obj\**" />
    <Compile Remove="Properties\AssemblyInfo.cs" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="obj\**" />
    <None Remove="*.bak" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="App.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.158" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(UpDir)\Libraries\MVVM_BaseLib\MVVM_BaseLib.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Models\Interfaces\" />
  </ItemGroup>
  <ItemGroup>
    <ReferencePath Include="C:\Projekte\CSharp\bin\BaseLib\Debug\net472\BaseLib.dll" />
    <ReferencePath Include="C:\Users\Mir\.nuget\packages\communitytoolkit.mvvm\8.4.2\lib\netstandard2.0\CommunityToolkit.Mvvm.dll" />
    <ReferencePath Include="C:\Users\Mir\.nuget\packages\microsoft.bcl.asyncinterfaces\10.0.11\lib\net462\Microsoft.Bcl.AsyncInterfaces.dll" />
    <ReferencePath Include="C:\Users\Mir\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\10.0.11\lib\net462\Microsoft.Extensions.DependencyInjection.Abstractions.dll" />
    <ReferencePath Include="C:\Users\Mir\.nuget\packages\microsoft.xaml.behaviors.wpf\1.1.158\lib\net462\Microsoft.Xaml.Behaviors.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\mscorlib.dll" />
    <ReferencePath Include="C:\Projekte\CSharp\bin\MVVM_BaseLib\Debug\net472\MVVM_BaseLib.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\PresentationCore.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\PresentationFramework.dll" />
    <ReferencePath Include="C:\Users\Mir\.nuget\packages\system.buffers\4.6.1\lib\net462\System.Buffers.dll" />
    <ReferencePath Include="C:\Users\Mir\.nuget\packages\system.componentmodel.annotations\5.0.0\ref\net461\System.ComponentModel.Annotations.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.ComponentModel.DataAnnotations.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Core.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Data.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Drawing.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.IO.Compression.FileSystem.dll" />
    <ReferencePath Include="C:\Users\Mir\.nuget\packages\system.memory\4.6.3\lib\net462\System.Memory.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Numerics.dll" />
    <ReferencePath Include="C:\Users\Mir\.nuget\packages\system.numerics.vectors\4.6.1\lib\net462\System.Numerics.Vectors.dll" />
    <ReferencePath Include="C:\Users\Mir\.nuget\packages\system.runtime.compilerservices.unsafe\6.1.2\lib\net462\System.Runtime.CompilerServices.Unsafe.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Runtime.Serialization.dll" />
    <ReferencePath Include="C:\Users\Mir\.nuget\packages\system.threading.tasks.extensions\4.6.3\lib\net462\System.Threading.Tasks.Extensions.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Windows.Controls.Ribbon.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Xaml.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Xml.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Xml.Linq.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\UIAutomationClient.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\UIAutomationClientsideProviders.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\UIAutomationProvider.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\UIAutomationTypes.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\WindowsBase.dll" />
    <ReferencePath Include="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\Facades\netstandard.dll" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="C:\Projekte\CSharp\obj\Polyline\Debug\net472\Views\MainWindow.g.cs" />
    <Compile Include="C:\Projekte\CSharp\obj\Polyline\Debug\net472\Views\PolyLineView.g.cs" />
    <Compile Include="C:\Projekte\CSharp\obj\Polyline\Debug\net472\App.g.cs" />
    <Compile Include="C:\Projekte\CSharp\obj\Polyline\Debug\net472\GeneratedInternalTypeHelper.g.cs" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="C:\Users\Mir\.nuget\packages\communitytoolkit.mvvm\8.4.2\analyzers\dotnet\roslyn5.0\cs\CommunityToolkit.Mvvm.CodeFixers.dll" />
    <Analyzer Include="C:\Users\Mir\.nuget\packages\communitytoolkit.mvvm\8.4.2\analyzers\dotnet\roslyn5.0\cs\CommunityToolkit.Mvvm.SourceGenerators.dll" />
  </ItemGroup>
</Project>