<Project>
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net8.0-windows</TargetFrameworks>
    </PropertyGroup>
    <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.props" />
    <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.targets" />
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Ollama.CodingAgent\Ollama.CodingAgent.csproj" />
        <ProjectReference Include="..\Ollama.CodingAgent.Application\Ollama.CodingAgent.Application.csproj" />
        <ProjectReference Include="..\Ollama.CodingAgent.Git\Ollama.CodingAgent.Git.csproj" />
        <ProjectReference Include="..\..\Data\CommandlineHelper\CommandlineHelper.csproj" />
        <ProjectReference Include="..\..\Data\CommandlineHelper.Generators\CommandlineHelper.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
        <ProjectReference Include="..\..\Libraries\ConsoleLib\ConsoleLib.csproj" />
        <ProjectReference Include="..\..\Libraries\ConsoleLib.ExtCon\ConsoleLib.ExtCon.csproj" />
    </ItemGroup>
</Project>
