<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Application.props" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>RnzTrauer.Places</RootNamespace>
    <AssemblyName>RnzTrauer.Places</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
</Project>
