// ***********************************************************************
// Assembly         : Calc32
// Author           : Mir
// Created          : 12-19-2021
//
// Last Modified By : Mir
// Last Modified On : 10-07-2022
// ***********************************************************************
// <copyright file="FrmCalc32Main.Designer.cs" company="JC-Soft">
//     Copyright © JC-Soft 2020
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using Calc32.Properties;
using Calc32.ViewModels.Interfaces;
using Views;

/// <summary>
/// The Visual namespace.
/// </summary>
/// <autogeneratedoc />
namespace Calc32.Visual
{
    /// <summary>
    /// Class FrmCalc32Main.
    /// Implements the <see cref="System.Windows.Forms.Form" />
    /// </summary>
    /// <seealso cref="System.Windows.Forms.Form" />
    partial class FrmCalc32Main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            btnNum1 = new System.Windows.Forms.Button();
            lblResult = new System.Windows.Forms.Label();
            pictureBox1 = new System.Windows.Forms.PictureBox();
            btnNum2 = new System.Windows.Forms.Button();
            btnNum3 = new System.Windows.Forms.Button();
            btnNum4 = new System.Windows.Forms.Button();
            btnNum5 = new System.Windows.Forms.Button();
            btnNum6 = new System.Windows.Forms.Button();
            btnNum7 = new System.Windows.Forms.Button();
            btnNum8 = new System.Windows.Forms.Button();
            btnNum9 = new System.Windows.Forms.Button();
            btnHexA = new System.Windows.Forms.Button();
            btnNum0 = new System.Windows.Forms.Button();
            btnToggleSign = new System.Windows.Forms.Button();
            lblOperation = new System.Windows.Forms.Label();
            lblMemory = new System.Windows.Forms.Label();
            btnBack = new System.Windows.Forms.Button();
            btnClear = new System.Windows.Forms.Button();
            btnClearAll = new System.Windows.Forms.Button();
            btnHexB = new System.Windows.Forms.Button();
            btnHexC = new System.Windows.Forms.Button();
            btnHexF = new System.Windows.Forms.Button();
            btnHexE = new System.Windows.Forms.Button();
            btnHexD = new System.Windows.Forms.Button();
            btnMult = new System.Windows.Forms.Button();
            btnDivide = new System.Windows.Forms.Button();
            btnPlus = new System.Windows.Forms.Button();
            btnMinus = new System.Windows.Forms.Button();
            btnResult = new System.Windows.Forms.Button();
            btnOpAnd = new System.Windows.Forms.Button();
            btnOpOR = new System.Windows.Forms.Button();
            btnOpXOR = new System.Windows.Forms.Button();
            btnOpNOT = new System.Windows.Forms.Button();
            pnlLeft = new System.Windows.Forms.Panel();
            panel2 = new System.Windows.Forms.Panel();
            pnlRight = new System.Windows.Forms.Panel();
            btnExtraFunction = new System.Windows.Forms.Button();
            button12 = new System.Windows.Forms.Button();
            pnlBottom = new System.Windows.Forms.Panel();
            btnClose = new System.Windows.Forms.Button();
            panel1 = new System.Windows.Forms.Panel();
            panel3 = new System.Windows.Forms.Panel();
            panel4 = new System.Windows.Forms.Panel();
            panel5 = new System.Windows.Forms.Panel();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).BeginInit();
            pnlLeft.SuspendLayout();
            SuspendLayout();
            // 
            // btnNum1
            // 
            btnNum1.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnNum1.AutoEllipsis = true;
            btnNum1.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnNum1.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnNum1.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnNum1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnNum1.Location = new System.Drawing.Point(605, 575);
            btnNum1.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnNum1.Name = "btnNum1";
            btnNum1.Size = new System.Drawing.Size(62, 73);
            btnNum1.TabIndex = 0;
            btnNum1.Tag = "1";
            btnNum1.Text = "1";
            btnNum1.UseVisualStyleBackColor = true;
            btnNum1.KeyDown += FrmCalc32Main_KeyDown;
            btnNum1.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // lblResult
            // 
            lblResult.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            lblResult.BackColor = System.Drawing.Color.FromArgb(192, 255, 240);
            lblResult.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            lblResult.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            lblResult.Location = new System.Drawing.Point(207, 90);
            lblResult.Name = "lblResult";
            lblResult.RightToLeft = System.Windows.Forms.RightToLeft.No;
            lblResult.Size = new System.Drawing.Size(740, 71);
            lblResult.TabIndex = 1;
            lblResult.Text = "0";
            lblResult.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            lblResult.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // pictureBox1
            // 
            pictureBox1.BackgroundImage = Resources.Glow_White;
            pictureBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            pictureBox1.Location = new System.Drawing.Point(1045, 737);
            pictureBox1.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Size = new System.Drawing.Size(217, 260);
            pictureBox1.TabIndex = 2;
            pictureBox1.TabStop = false;
            pictureBox1.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnNum2
            // 
            btnNum2.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnNum2.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnNum2.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnNum2.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnNum2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnNum2.Location = new System.Drawing.Point(675, 575);
            btnNum2.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnNum2.Name = "btnNum2";
            btnNum2.Size = new System.Drawing.Size(62, 73);
            btnNum2.TabIndex = 4;
            btnNum2.Tag = "2";
            btnNum2.Text = "2";
            btnNum2.UseVisualStyleBackColor = true;
            btnNum2.KeyDown += FrmCalc32Main_KeyDown;
            btnNum2.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnNum3
            // 
            btnNum3.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnNum3.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnNum3.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnNum3.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnNum3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnNum3.Location = new System.Drawing.Point(743, 575);
            btnNum3.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnNum3.Name = "btnNum3";
            btnNum3.Size = new System.Drawing.Size(62, 73);
            btnNum3.TabIndex = 5;
            btnNum3.Tag = "3";
            btnNum3.Text = "3";
            btnNum3.UseVisualStyleBackColor = true;
            btnNum3.KeyDown += FrmCalc32Main_KeyDown;
            btnNum3.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnNum4
            // 
            btnNum4.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnNum4.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnNum4.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnNum4.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnNum4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnNum4.Location = new System.Drawing.Point(605, 494);
            btnNum4.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnNum4.Name = "btnNum4";
            btnNum4.Size = new System.Drawing.Size(62, 73);
            btnNum4.TabIndex = 6;
            btnNum4.Tag = "4";
            btnNum4.Text = "4";
            btnNum4.UseVisualStyleBackColor = true;
            btnNum4.KeyDown += FrmCalc32Main_KeyDown;
            btnNum4.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnNum5
            // 
            btnNum5.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnNum5.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnNum5.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnNum5.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnNum5.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnNum5.Location = new System.Drawing.Point(675, 494);
            btnNum5.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnNum5.Name = "btnNum5";
            btnNum5.Size = new System.Drawing.Size(62, 73);
            btnNum5.TabIndex = 7;
            btnNum5.Tag = "5";
            btnNum5.Text = "5";
            btnNum5.UseVisualStyleBackColor = true;
            btnNum5.KeyDown += FrmCalc32Main_KeyDown;
            btnNum5.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnNum6
            // 
            btnNum6.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnNum6.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnNum6.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnNum6.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnNum6.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnNum6.Location = new System.Drawing.Point(743, 494);
            btnNum6.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnNum6.Name = "btnNum6";
            btnNum6.Size = new System.Drawing.Size(62, 73);
            btnNum6.TabIndex = 8;
            btnNum6.Tag = "6";
            btnNum6.Text = "6";
            btnNum6.UseVisualStyleBackColor = true;
            btnNum6.KeyDown += FrmCalc32Main_KeyDown;
            btnNum6.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnNum7
            // 
            btnNum7.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnNum7.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnNum7.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnNum7.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnNum7.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnNum7.Location = new System.Drawing.Point(605, 412);
            btnNum7.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnNum7.Name = "btnNum7";
            btnNum7.Size = new System.Drawing.Size(62, 73);
            btnNum7.TabIndex = 9;
            btnNum7.Tag = "7";
            btnNum7.Text = "7";
            btnNum7.UseVisualStyleBackColor = true;
            btnNum7.KeyDown += FrmCalc32Main_KeyDown;
            btnNum7.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnNum8
            // 
            btnNum8.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnNum8.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnNum8.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnNum8.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnNum8.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnNum8.Location = new System.Drawing.Point(675, 412);
            btnNum8.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnNum8.Name = "btnNum8";
            btnNum8.Size = new System.Drawing.Size(62, 73);
            btnNum8.TabIndex = 10;
            btnNum8.Tag = "8";
            btnNum8.Text = "8";
            btnNum8.UseVisualStyleBackColor = true;
            btnNum8.KeyDown += FrmCalc32Main_KeyDown;
            btnNum8.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnNum9
            // 
            btnNum9.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnNum9.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnNum9.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnNum9.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnNum9.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnNum9.Location = new System.Drawing.Point(743, 412);
            btnNum9.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnNum9.Name = "btnNum9";
            btnNum9.Size = new System.Drawing.Size(62, 73);
            btnNum9.TabIndex = 11;
            btnNum9.Tag = "9";
            btnNum9.Text = "9";
            btnNum9.UseVisualStyleBackColor = true;
            btnNum9.KeyDown += FrmCalc32Main_KeyDown;
            btnNum9.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnHexA
            // 
            btnHexA.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnHexA.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnHexA.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnHexA.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnHexA.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnHexA.Location = new System.Drawing.Point(605, 331);
            btnHexA.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnHexA.Name = "btnHexA";
            btnHexA.Size = new System.Drawing.Size(62, 73);
            btnHexA.TabIndex = 12;
            btnHexA.Tag = "10";
            btnHexA.Text = "A";
            btnHexA.UseVisualStyleBackColor = true;
            btnHexA.KeyDown += FrmCalc32Main_KeyDown;
            btnHexA.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnNum0
            // 
            btnNum0.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnNum0.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnNum0.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnNum0.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnNum0.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnNum0.Location = new System.Drawing.Point(605, 656);
            btnNum0.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnNum0.Name = "btnNum0";
            btnNum0.Size = new System.Drawing.Size(132, 73);
            btnNum0.TabIndex = 13;
            btnNum0.Tag = "0";
            btnNum0.Text = "0";
            btnNum0.UseVisualStyleBackColor = true;
            btnNum0.KeyDown += FrmCalc32Main_KeyDown;
            btnNum0.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnToggleSign
            // 
            btnToggleSign.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnToggleSign.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnToggleSign.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnToggleSign.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnToggleSign.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnToggleSign.Location = new System.Drawing.Point(743, 656);
            btnToggleSign.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnToggleSign.Name = "btnToggleSign";
            btnToggleSign.Size = new System.Drawing.Size(62, 73);
            btnToggleSign.TabIndex = 14;
            btnToggleSign.Tag = "10";
            btnToggleSign.Text = "+/-";
            btnToggleSign.UseVisualStyleBackColor = true;
            btnToggleSign.KeyDown += FrmCalc32Main_KeyDown;
            btnToggleSign.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // lblOperation
            // 
            lblOperation.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            lblOperation.BackColor = System.Drawing.Color.FromArgb(192, 255, 240);
            lblOperation.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            lblOperation.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            lblOperation.Location = new System.Drawing.Point(828, 12);
            lblOperation.Name = "lblOperation";
            lblOperation.RightToLeft = System.Windows.Forms.RightToLeft.No;
            lblOperation.Size = new System.Drawing.Size(118, 71);
            lblOperation.TabIndex = 15;
            lblOperation.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            lblOperation.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // lblMemory
            // 
            lblMemory.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            lblMemory.BackColor = System.Drawing.Color.FromArgb(192, 255, 240);
            lblMemory.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            lblMemory.Font = new System.Drawing.Font("Microsoft Sans Serif", 14F, System.Drawing.FontStyle.Italic, System.Drawing.GraphicsUnit.Point);
            lblMemory.Location = new System.Drawing.Point(207, 12);
            lblMemory.Name = "lblMemory";
            lblMemory.RightToLeft = System.Windows.Forms.RightToLeft.No;
            lblMemory.Size = new System.Drawing.Size(615, 71);
            lblMemory.TabIndex = 16;
            lblMemory.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            lblMemory.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnBack
            // 
            btnBack.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            btnBack.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnBack.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnBack.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnBack.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnBack.Location = new System.Drawing.Point(138, 250);
            btnBack.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnBack.Name = "btnBack";
            btnBack.Size = new System.Drawing.Size(132, 73);
            btnBack.TabIndex = 17;
            btnBack.Tag = "2";
            btnBack.Text = "<==";
            btnBack.UseVisualStyleBackColor = true;
            btnBack.Click += btnBack_Click;
            btnBack.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnClear
            // 
            btnClear.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnClear.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnClear.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnClear.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnClear.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnClear.Location = new System.Drawing.Point(398, 250);
            btnClear.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnClear.Name = "btnClear";
            btnClear.Size = new System.Drawing.Size(132, 73);
            btnClear.TabIndex = 18;
            btnClear.Tag = "-1";
            btnClear.Text = "C";
            btnClear.UseVisualStyleBackColor = true;
            btnClear.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnClearAll
            // 
            btnClearAll.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnClearAll.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnClearAll.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnClearAll.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnClearAll.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnClearAll.Location = new System.Drawing.Point(398, 331);
            btnClearAll.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnClearAll.Name = "btnClearAll";
            btnClearAll.Size = new System.Drawing.Size(132, 73);
            btnClearAll.TabIndex = 19;
            btnClearAll.Tag = "-3";
            btnClearAll.Text = "&CE";
            btnClearAll.UseVisualStyleBackColor = true;
            btnClearAll.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnHexB
            // 
            btnHexB.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnHexB.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnHexB.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnHexB.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnHexB.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnHexB.Location = new System.Drawing.Point(675, 331);
            btnHexB.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnHexB.Name = "btnHexB";
            btnHexB.Size = new System.Drawing.Size(62, 73);
            btnHexB.TabIndex = 20;
            btnHexB.Tag = "11";
            btnHexB.Text = "B";
            btnHexB.UseVisualStyleBackColor = true;
            btnHexB.Click += btnNumber_Click;
            btnHexB.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnHexC
            // 
            btnHexC.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnHexC.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnHexC.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnHexC.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnHexC.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnHexC.Location = new System.Drawing.Point(743, 331);
            btnHexC.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnHexC.Name = "btnHexC";
            btnHexC.Size = new System.Drawing.Size(62, 73);
            btnHexC.TabIndex = 21;
            btnHexC.Tag = "12";
            btnHexC.Text = "C";
            btnHexC.UseVisualStyleBackColor = true;
            btnHexC.Click += btnNumber_Click;
            btnHexC.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnHexF
            // 
            btnHexF.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnHexF.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnHexF.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnHexF.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnHexF.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnHexF.Location = new System.Drawing.Point(743, 250);
            btnHexF.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnHexF.Name = "btnHexF";
            btnHexF.Size = new System.Drawing.Size(62, 73);
            btnHexF.TabIndex = 24;
            btnHexF.Tag = "15";
            btnHexF.Text = "F";
            btnHexF.UseVisualStyleBackColor = true;
            btnHexF.Click += btnNumber_Click;
            btnHexF.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnHexE
            // 
            btnHexE.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnHexE.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnHexE.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnHexE.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnHexE.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnHexE.Location = new System.Drawing.Point(675, 250);
            btnHexE.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnHexE.Name = "btnHexE";
            btnHexE.Size = new System.Drawing.Size(62, 73);
            btnHexE.TabIndex = 23;
            btnHexE.Tag = "14";
            btnHexE.Text = "E";
            btnHexE.UseVisualStyleBackColor = true;
            btnHexE.Click += btnNumber_Click;
            btnHexE.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnHexD
            // 
            btnHexD.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnHexD.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnHexD.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnHexD.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnHexD.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnHexD.Location = new System.Drawing.Point(605, 250);
            btnHexD.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnHexD.Name = "btnHexD";
            btnHexD.Size = new System.Drawing.Size(62, 73);
            btnHexD.TabIndex = 22;
            btnHexD.Tag = "13";
            btnHexD.Text = "D";
            btnHexD.UseVisualStyleBackColor = true;
            btnHexD.Click += btnNumber_Click;
            btnHexD.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnMult
            // 
            btnMult.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnMult.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnMult.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnMult.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnMult.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnMult.Location = new System.Drawing.Point(537, 250);
            btnMult.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnMult.Name = "btnMult";
            btnMult.Size = new System.Drawing.Size(62, 73);
            btnMult.TabIndex = 29;
            btnMult.Tag = "4";
            btnMult.Text = "*";
            btnMult.UseVisualStyleBackColor = true;
            btnMult.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnDivide
            // 
            btnDivide.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnDivide.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnDivide.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnDivide.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnDivide.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnDivide.Location = new System.Drawing.Point(537, 331);
            btnDivide.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnDivide.Name = "btnDivide";
            btnDivide.Size = new System.Drawing.Size(62, 73);
            btnDivide.TabIndex = 28;
            btnDivide.Tag = "5";
            btnDivide.Text = "/";
            btnDivide.UseVisualStyleBackColor = true;
            btnDivide.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnPlus
            // 
            btnPlus.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnPlus.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnPlus.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnPlus.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnPlus.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnPlus.Location = new System.Drawing.Point(537, 412);
            btnPlus.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnPlus.Name = "btnPlus";
            btnPlus.Size = new System.Drawing.Size(62, 73);
            btnPlus.TabIndex = 27;
            btnPlus.Tag = "2";
            btnPlus.Text = "+";
            btnPlus.UseVisualStyleBackColor = true;
            btnPlus.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnMinus
            // 
            btnMinus.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnMinus.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnMinus.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnMinus.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnMinus.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnMinus.Location = new System.Drawing.Point(537, 494);
            btnMinus.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnMinus.Name = "btnMinus";
            btnMinus.Size = new System.Drawing.Size(62, 73);
            btnMinus.TabIndex = 26;
            btnMinus.Tag = "3";
            btnMinus.Text = "-";
            btnMinus.UseVisualStyleBackColor = true;
            btnMinus.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnResult
            // 
            btnResult.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnResult.AutoEllipsis = true;
            btnResult.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnResult.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnResult.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnResult.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnResult.Location = new System.Drawing.Point(537, 575);
            btnResult.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnResult.Name = "btnResult";
            btnResult.Size = new System.Drawing.Size(62, 156);
            btnResult.TabIndex = 25;
            btnResult.Tag = "1";
            btnResult.Text = "=";
            btnResult.UseVisualStyleBackColor = true;
            btnResult.KeyDown += FrmCalc32Main_KeyDown;
            btnResult.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnOpAnd
            // 
            btnOpAnd.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnOpAnd.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnOpAnd.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnOpAnd.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnOpAnd.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnOpAnd.Location = new System.Drawing.Point(812, 250);
            btnOpAnd.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnOpAnd.Name = "btnOpAnd";
            btnOpAnd.Size = new System.Drawing.Size(133, 113);
            btnOpAnd.TabIndex = 33;
            btnOpAnd.Tag = "6";
            btnOpAnd.Text = "AND";
            btnOpAnd.UseVisualStyleBackColor = true;
            btnOpAnd.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnOpOR
            // 
            btnOpOR.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnOpOR.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnOpOR.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnOpOR.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnOpOR.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnOpOR.Location = new System.Drawing.Point(812, 373);
            btnOpOR.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnOpOR.Name = "btnOpOR";
            btnOpOR.Size = new System.Drawing.Size(133, 113);
            btnOpOR.TabIndex = 32;
            btnOpOR.Tag = "7";
            btnOpOR.Text = "OR";
            btnOpOR.UseVisualStyleBackColor = true;
            btnOpOR.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnOpXOR
            // 
            btnOpXOR.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnOpXOR.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnOpXOR.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnOpXOR.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnOpXOR.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnOpXOR.Location = new System.Drawing.Point(812, 494);
            btnOpXOR.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnOpXOR.Name = "btnOpXOR";
            btnOpXOR.Size = new System.Drawing.Size(133, 113);
            btnOpXOR.TabIndex = 31;
            btnOpXOR.Tag = "8";
            btnOpXOR.Text = "XOR";
            btnOpXOR.UseVisualStyleBackColor = true;
            btnOpXOR.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnOpNOT
            // 
            btnOpNOT.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            btnOpNOT.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnOpNOT.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnOpNOT.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnOpNOT.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnOpNOT.Location = new System.Drawing.Point(812, 617);
            btnOpNOT.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnOpNOT.Name = "btnOpNOT";
            btnOpNOT.Size = new System.Drawing.Size(133, 113);
            btnOpNOT.TabIndex = 30;
            btnOpNOT.Tag = "9";
            btnOpNOT.Text = "NOT";
            btnOpNOT.UseVisualStyleBackColor = true;
            btnOpNOT.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // pnlLeft
            // 
            pnlLeft.Controls.Add(panel2);
            pnlLeft.Dock = System.Windows.Forms.DockStyle.Left;
            pnlLeft.Location = new System.Drawing.Point(0, 0);
            pnlLeft.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            pnlLeft.Name = "pnlLeft";
            pnlLeft.Size = new System.Drawing.Size(132, 867);
            pnlLeft.TabIndex = 34;
            pnlLeft.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // panel2
            // 
            panel2.Location = new System.Drawing.Point(132, 331);
            panel2.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            panel2.Name = "panel2";
            panel2.Size = new System.Drawing.Size(260, 283);
            panel2.TabIndex = 41;
            // 
            // pnlRight
            // 
            pnlRight.Dock = System.Windows.Forms.DockStyle.Right;
            pnlRight.Location = new System.Drawing.Point(953, 0);
            pnlRight.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            pnlRight.Name = "pnlRight";
            pnlRight.Size = new System.Drawing.Size(132, 867);
            pnlRight.TabIndex = 35;
            pnlRight.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnExtraFunction
            // 
            btnExtraFunction.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnExtraFunction.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnExtraFunction.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnExtraFunction.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnExtraFunction.Location = new System.Drawing.Point(138, 10);
            btnExtraFunction.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnExtraFunction.Name = "btnExtraFunction";
            btnExtraFunction.Size = new System.Drawing.Size(62, 73);
            btnExtraFunction.TabIndex = 36;
            btnExtraFunction.Tag = "4";
            btnExtraFunction.Text = "X1";
            btnExtraFunction.UseVisualStyleBackColor = true;
            btnExtraFunction.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // button12
            // 
            button12.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            button12.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            button12.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            button12.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            button12.Location = new System.Drawing.Point(138, 90);
            button12.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            button12.Name = "button12";
            button12.Size = new System.Drawing.Size(62, 73);
            button12.TabIndex = 37;
            button12.Tag = "4";
            button12.Text = "X2";
            button12.UseVisualStyleBackColor = true;
            button12.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // pnlBottom
            // 
            pnlBottom.Dock = System.Windows.Forms.DockStyle.Bottom;
            pnlBottom.Location = new System.Drawing.Point(132, 742);
            pnlBottom.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            pnlBottom.Name = "pnlBottom";
            pnlBottom.Size = new System.Drawing.Size(821, 125);
            pnlBottom.TabIndex = 38;
            pnlBottom.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // btnClose
            // 
            btnClose.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            btnClose.BackgroundImage = Resources.Exit;
            btnClose.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            btnClose.DialogResult = System.Windows.Forms.DialogResult.OK;
            btnClose.FlatAppearance.BorderColor = System.Drawing.SystemColors.Control;
            btnClose.FlatAppearance.MouseOverBackColor = System.Drawing.Color.Lavender;
            btnClose.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnClose.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            btnClose.Location = new System.Drawing.Point(138, 621);
            btnClose.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            btnClose.Name = "btnClose";
            btnClose.Size = new System.Drawing.Size(230, 113);
            btnClose.TabIndex = 39;
            btnClose.Tag = "0";
            btnClose.Text = Resources.btnClose;
            btnClose.UseVisualStyleBackColor = true;
            btnClose.Click += btnClose_Click;
            btnClose.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // panel1
            // 
            panel1.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            panel1.Location = new System.Drawing.Point(375, 413);
            panel1.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            panel1.Name = "panel1";
            panel1.Size = new System.Drawing.Size(155, 340);
            panel1.TabIndex = 40;
            panel1.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // panel3
            // 
            panel3.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            panel3.Location = new System.Drawing.Point(132, 331);
            panel3.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            panel3.Name = "panel3";
            panel3.Size = new System.Drawing.Size(262, 281);
            panel3.TabIndex = 41;
            panel3.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // panel4
            // 
            panel4.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            panel4.Location = new System.Drawing.Point(130, 171);
            panel4.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            panel4.Name = "panel4";
            panel4.Size = new System.Drawing.Size(825, 69);
            panel4.TabIndex = 45;
            panel4.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // panel5
            // 
            panel5.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            panel5.Location = new System.Drawing.Point(275, 240);
            panel5.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            panel5.Name = "panel5";
            panel5.Size = new System.Drawing.Size(117, 98);
            panel5.TabIndex = 46;
            panel5.MouseMove += FrmCalc32Main_MouseMove;
            // 
            // FrmCalc32Main
            // 
            AutoScaleDimensions = new System.Drawing.SizeF(10F, 25F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.SystemColors.ControlLight;
            ClientSize = new System.Drawing.Size(1085, 867);
            Controls.Add(panel5);
            Controls.Add(panel4);
            Controls.Add(panel3);
            Controls.Add(panel1);
            Controls.Add(btnClose);
            Controls.Add(pnlBottom);
            Controls.Add(button12);
            Controls.Add(btnExtraFunction);
            Controls.Add(pnlRight);
            Controls.Add(pnlLeft);
            Controls.Add(btnOpAnd);
            Controls.Add(btnOpOR);
            Controls.Add(btnOpXOR);
            Controls.Add(btnOpNOT);
            Controls.Add(btnMult);
            Controls.Add(btnDivide);
            Controls.Add(btnPlus);
            Controls.Add(btnMinus);
            Controls.Add(btnResult);
            Controls.Add(btnHexF);
            Controls.Add(btnHexE);
            Controls.Add(btnHexD);
            Controls.Add(btnHexC);
            Controls.Add(btnHexB);
            Controls.Add(btnClearAll);
            Controls.Add(btnClear);
            Controls.Add(btnBack);
            Controls.Add(lblMemory);
            Controls.Add(lblOperation);
            Controls.Add(btnToggleSign);
            Controls.Add(btnNum0);
            Controls.Add(btnHexA);
            Controls.Add(btnNum9);
            Controls.Add(btnNum8);
            Controls.Add(btnNum7);
            Controls.Add(btnNum6);
            Controls.Add(btnNum5);
            Controls.Add(btnNum4);
            Controls.Add(btnNum3);
            Controls.Add(btnNum2);
            Controls.Add(lblResult);
            Controls.Add(btnNum1);
            Controls.Add(pictureBox1);
            Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            Name = "FrmCalc32Main";
            Text = "FrmCalc32Main .NET 6.0";
            Click += btnOperator_Click;
            KeyDown += FrmCalc32Main_KeyDown;
            MouseMove += FrmCalc32Main_MouseMove;
            ((System.ComponentModel.ISupportInitialize)pictureBox1).EndInit();
            pnlLeft.ResumeLayout(false);
            ResumeLayout(false);
        }

        #endregion
        /// <summary>
        /// The label result
        /// </summary>
        [TextBinding(nameof(ICalculatorViewModel.Accumulator))]
        public System.Windows.Forms.Label lblResult;
        /// <summary>
        /// The picture box1
        /// </summary>
        private System.Windows.Forms.PictureBox pictureBox1;
        /// <summary>
        /// The btnNum2
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnNum2;
        /// <summary>
        /// The btnNum3
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnNum3;
        /// <summary>
        /// The btnNum4
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnNum4;
        /// <summary>
        /// The btnNum5
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnNum5;
        /// <summary>
        /// The btnNum6
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnNum6;
        /// <summary>
        /// The btnNum7
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnNum7;
        /// <summary>
        /// The btnNum8
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnNum8;
        /// <summary>
        /// The btnNum9
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnNum9;
        /// <summary>
        /// The BTN hexadecimal a
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnHexA;
        /// <summary>
        /// The btnNum0
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnNum0;
        /// <summary>
        /// The btnToggleSign
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnToggleSign;
        /// <summary>
        /// The label operation
        /// </summary>
        [TextBinding(nameof(ICalculatorViewModel.OperationText))]
        private System.Windows.Forms.Label lblOperation;
        /// <summary>
        /// The label memory
        /// </summary>
        [TextBinding(nameof(ICalculatorViewModel.Memory))]
        private System.Windows.Forms.Label lblMemory;
        /// <summary>
        /// The BTN clear
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnClear;
        /// <summary>
        /// The BTN clear all
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnClearAll;
        /// <summary>
        /// The BTN hexadecimal b
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnHexB;
        /// <summary>
        /// The BTN hexadecimal c
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnHexC;
        /// <summary>
        /// The BTN hexadecimal f
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnHexF;
        /// <summary>
        /// The BTN hexadecimal e
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnHexE;
        /// <summary>
        /// The BTN hexadecimal d
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        private System.Windows.Forms.Button btnHexD;
        /// <summary>
        /// The BTN mult
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnMult;
        /// <summary>
        /// The BTN divide
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnDivide;
        /// <summary>
        /// The BTN plus
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnPlus;
        /// <summary>
        /// The BTN minus
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnMinus;
        /// <summary>
        /// The BTN op and
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnOpAnd;
        /// <summary>
        /// The BTN op or
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnOpOR;
        /// <summary>
        /// The BTN op xor
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnOpXOR;
        /// <summary>
        /// The BTN op not
        /// </summary>
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        private System.Windows.Forms.Button btnOpNOT;
        /// <summary>
        /// The PNL left
        /// </summary>
        private System.Windows.Forms.Panel pnlLeft;
        /// <summary>
        /// The PNL right
        /// </summary>
        private System.Windows.Forms.Panel pnlRight;
        /// <summary>
        /// The panel2
        /// </summary>
        private System.Windows.Forms.Panel panel2;
        /// <summary>
        /// The btnExtraFunction
        /// </summary>
        private System.Windows.Forms.Button btnExtraFunction;
        /// <summary>
        /// The button12
        /// </summary>
        private System.Windows.Forms.Button button12;
        /// <summary>
        /// The PNL bottom
        /// </summary>
        private System.Windows.Forms.Panel pnlBottom;
        /// <summary>
        /// The BTN close
        /// </summary>
        private System.Windows.Forms.Button btnClose;
        /// <summary>
        /// The panel1
        /// </summary>
        private System.Windows.Forms.Panel panel1;
        /// <summary>
        /// The panel3
        /// </summary>
        private System.Windows.Forms.Panel panel3;
        /// <summary>
        /// The panel4
        /// </summary>
        private System.Windows.Forms.Panel panel4;
        /// <summary>
        /// The panel5
        /// </summary>
        private System.Windows.Forms.Panel panel5;
        [CommandBinding(nameof(ICalculatorViewModel.NumberCommand))]
        public System.Windows.Forms.Button btnNum1;
        public System.Windows.Forms.Button btnBack;
        [CommandBinding(nameof(ICalculatorViewModel.OperationCommand))]
        public System.Windows.Forms.Button btnResult;
    }
}