<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\BaseLib\BaseLib.csproj" />
    <ProjectReference Include="..\..\Libraries\ConsoleLib\ConsoleLib.csproj" />
    <ProjectReference Include="..\..\Libraries\ConsoleLib.ExtCon\ConsoleLib.ExtCon.csproj" />
    <ProjectReference Include="..\DetectiveGame.Console\DetectiveGame.Console.csproj" />
    <ProjectReference Include="..\DetectiveGame.Engine\DetectiveGame.Engine.csproj" />
    <EmbeddedResource Include="Views\Main.cxaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
