namespace WinAhnenCls.Model.HejInd
{
    public enum EHejIndDataFields
    {
        hind_ID = -1,
        hind_idFather = 0,
        hind_idMother = 1,
        hind_FamilyName = 2,
        hind_GivenName = 3,
        hind_Sex = 4,
        hind_Religion = 5,
        hind_Occupation = 6,
        hind_BirthDay = 7,
        hind_BirthMonth = 8,
        hind_BirthYear = 9,
        hind_BirthPlace = 10,
        hind_BaptDay = 11,
        hind_BaptMonth = 12,
        hind_BaptYear = 13,
        hind_BaptPlace = 14,
        hind_Godparents = 15,
        hind_Residence = 16,
        hind_DeathDay = 17,
        hind_DeathMonth = 18,
        hind_DeathYear = 19,
        hind_DeathPlace = 20,
        hind_DeathReason = 21,
        hind_BurialDay = 22,
        hind_BurialMonth = 23,
        hind_BurialYear = 24,
        hind_BurialPlace = 25,
        hind_BirthSource = 26,
        hind_BaptSource = 27,
        hind_DeathSource = 28,
        hind_BurialSource = 29,
        hind_Text = 30,
        hind_Living = 31,
        hind_AKA = 32,
        hind_Index = 33,
        hind_Adopted = 34,
        hind_FarmName = 35,
        hind_AdrStreet = 36,
        hind_AdrAddit = 37,
        hind_AdrPLZ = 38,
        hind_AdrPlace = 39,
        hind_AdrPlaceAdd = 40,
        hind_Free1 = 41,
        hind_Free2 = 42,
        hind_Free3 = 43,
        hind_Age = 44,
        hind_Phone = 45,
        hind_eMail = 46,
        hind_WebAdr = 47,
        hind_NameSource = 48,
        hind_CallName = 49
    }
}
