<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="MSTest.TestAdapter" VersionOverride="4.3.3" />
    <PackageReference Include="MSTest.TestFramework" VersionOverride="4.3.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Leonardo.ST.Cxaml\Leonardo.ST.Cxaml.csproj" />
  </ItemGroup>
</Project>
