using CommunityToolkit.Mvvm.Input;
using GenFree.Helper;
using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows.Forms;

namespace GenFree.ViewModels.Interfaces;

public interface INamenSuchViewModel : INotifyPropertyChanged
{
    IContainerControl View { get; set; }
    // ====================================================================
    // Filter & Visibility State
    // ====================================================================
    bool Male_Checked { get; set; }
    bool Females_Checked { get; set; }
    bool FamOnly_Checked { get; set; }
    bool Selection_Checked { get; set; }
    bool Male2_Checked { get; set; }
    bool Female2_Checked { get; set; }
    bool OmitSpouse_Checked { get; set; }

    // ====================================================================
    // Search Input & Results
    // ====================================================================
    string Text1_Text { get; set; }
    string Text2_Text { get; set; }
    int PersNr { get; set; }
    int FamNr { get; set; }

    // ====================================================================
    // Service Layer State (NEW: For service integration feedback)
    // ====================================================================
    bool IsLoading { get; }
    string StatusMessage { get; }
    int SearchResultCount { get; }

    // ====================================================================
    // Lifecycle & Core Commands
    // ====================================================================
    IRelayCommand FormLoadCommand { get; }
    IRelayCommand FormClosedCommand { get; }
    IRelayCommand CloseCommand { get; }

    // ====================================================================
    // Search & Filter Commands (Modern Service-Driven)
    // ====================================================================
    IAsyncRelayCommand ExecuteSearchCommand { get; }  // NEW: Service-driven async search (Phase B+)
    IRelayCommand StartSearchCommand { get; }         // LEGACY: Direct event handler (backward compat)
    IRelayCommand ClearResultsCommand { get; }
    IRelayCommand<string> SearchTextChangedCommand { get; }
    IRelayCommand RegisterSearch_ClickCommand { get; }

    // ====================================================================
    // Gender & Mode Filter Commands (auto-generated by [RelayCommand])
    // ====================================================================
    IRelayCommand FamOnlyCheckedCommand { get; }
    IRelayCommand OmitSpouseToggledCommand { get; }
    IRelayCommand CheckMaleCommand { get; }
    IRelayCommand CheckFemaleCommand { get; }
    IRelayCommand CheckMale2Command { get; }
    IRelayCommand CheckFemale2Command { get; }

    // ====================================================================
    // Sheet Display Commands
    // ====================================================================
    IRelayCommand PersonSheetCommand { get; }
    IRelayCommand FamilySheetCommand { get; }
    IRelayCommand PrintListCommand { get; }

    // ====================================================================
    // Item Selection & Action Commands
    // ====================================================================
    IRelayCommand<GenFree.Helper.ListItem<int>> SelectListItemCommand { get; }
    IRelayCommand<int> Label6_DoubleClickCommand { get; }
    IRelayCommand<int> Label5_DoubleClickCommand { get; }
    IRelayCommand ReqHintCommand { get; }
    IRelayCommand ReqInfoCommand { get; }

    bool xComboBox2AddT308 { get; }
    bool xComboBox2AddT309 { get; }
    int FamPerschalt { get; set; }

    // ====================================================================
    // Collections for List/ComboBox Binding
    // ====================================================================
    ObservableCollection<ListItem<int>> Label1_Text { get; }
    ObservableCollection<ListItem<int>> Label5_Text { get; }
    ObservableCollection<ListItem<int>> Label7_Text { get; }
    ObservableCollection<ListItem<int>> ListBox1_Items { get; }
    ObservableCollection<ListItem<int>> ComboBox1_Items { get; }

    // ====================================================================
    // Methods
    // ====================================================================
    Action DoHide { get; set; }

    void SetPerson(int value, int an, short schalt);
    void ShowNamensuchDlg(string title, int personNr, int iFamNr);
}