//***************************************************************
// Assembly         : SomeGame_Base
// Author           : Mir
// Created          : 01-01-2025
//
// Last Modified By : Mir
// Last Modified On : 01-01-2025
// ***********************************************************************
// <copyright file="VTileDef.cs" company="JC-Soft">
//     Copyright (c) JC-Soft. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using ConsoleDisplay.View;
using System.Drawing;

/// <summary>
/// The View namespace.
/// </summary>
/// <autogeneratedoc />
namespace Console.Views;

/// <summary>
/// Class TileDef.
/// Implements the <see cref="TileDef{Tiles}" /></summary>
/// <seealso cref="TileDef{Tiles}" />
public class TileDef : TileDefBase
{
    /// <summary>
    /// The tile definition string
    /// </summary>
    private readonly string[][] _vTileDefStr = [
        [@"    "], //Empty
        [@"[_|]", @"[|_]"], //Wall
        [@". . ", @" . ."], //Floor
        [@"    ", @"<==>"], //Destination
        [@"|()|", @"(__)"], //Player
        [@" <°)", @">_|_"], //PlayerOverDest
        [@"/^^\", @"\__/"], //Stone
        [@",--,", @"|__|"], //StoneInDest
        [@". . ", @" . ."], //Floor_Marked
        [@"[_|]", @"[|_]"], //Wall_N
        [@"|_|]", @"_|_]"], //Wall_W
        [@"|_|]", @"_|_]"], //Wall_NW
        [@"[_|]", @"[|_]"], //Wall_S
        [@"[_|]", @"[|_]"], //Wall_NS
        [@"|_|]", @"_|_]"], //Wall_WS
        [@"|_|]", @"_|_]"], //Wall_NWS
        [@"[_|_", @"[|_|"], //Wall_E
        [@"[_|_", @"[|_|"], //Wall_NE
        [@"|_|_", @"_|_|"], //Wall_WE
        [@"|_|_", @"_|_|"], //Wall_NWE
        [@"[_|_", @"[|_|"], //Wall_SE
        [@"[_|_", @"[|_|"], //Wall_NSE
        [@"|_|_", @"_|_|"], //Wall_WSE
        [@"|_|_", @"_|_|"], //Wall_NWSE
        [@" <°)", @">-||"], //Player_W
        [@" <°)", @">_|_"], //PlayerOverDest_W
        [@"(°°)", @"|^^|"], //Player_S
        [@" <°)", @">_|_"], //PlayerOverDest_S
        [@"(°> ", @"||-<"], //Player_E
        [@" <°)", @">_|_"], //PlayerOverDest_E
    ];


    /// <summary>
    /// The tile colors
    /// </summary>
    private readonly byte[][] _vTileColors = [
        [0x07], //Empty
        [0x47], //Wall
        [0x2A], //Floor
        [0x2F], //Destination
        [0x2F], //Player
        [0x2F], //PlayerOverDest
        [0x6E], //Stone
        [0x6F], //StoneInDest
        [0x2A], //Floor_Marked
        [0x47], //Wall_N
        [0x47], //Wall_W
        [0x47], //Wall_NW
        [0x47], //Wall_S
        [0x47], //Wall_NS
        [0x47], //Wall_WS
        [0x47], //Wall_NWS
        [0x47], //Wall_E
        [0x47], //Wall_NE
        [0x47], //Wall_WE
        [0x47], //Wall_NWE
        [0x47], //Wall_SE
        [0x47], //Wall_NSE
        [0x47], //Wall_WSE
        [0x47], //Wall_NWSE
        [0x2F], //Player_W
        [0x2F], //PlayerOverDest_W
        [0x2F], //Player_S
        [0x2F], //PlayerOverDest_S
        [0x2F], //Player_E
        [0x2F], //PlayerOverDest_E
    ];

    /// <summary>
    /// Gets the tile definition.
    /// </summary>
    /// <param name="tile">The tile.</param>
    /// <returns>(string[] lines, (System.ConsoleColor fgr, System.ConsoleColor bgr)[] colors).</returns>
    /// <autogeneratedoc />
    public override (string[] lines, (ConsoleColor fgr, ConsoleColor bgr)[] colors) GetTileDef(Enum? tile)
    {
        (string[] lines, (ConsoleColor fgr, ConsoleColor bgr)[] colors) result = default;
        result.lines = GetArrayElement(_vTileDefStr, tile);

        result.colors = new (ConsoleColor fgr, ConsoleColor bgr)[result.lines.Length * result.lines[0].Length];
        byte[] colDef = GetArrayElement(_vTileColors, tile);
        for (var i = 0; i < result.lines.Length * result.lines[0].Length; i++)
            result.colors[i] = ByteTo2ConsColor(colDef[i % colDef.Length]);
        return result;
    }

    public TileDef() : base() => TileSize = new Size(4, 2);
}