//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MoveWindow.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_MoveWindow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Window ähnelt.
        /// </summary>
        public static string btnMove {
            get {
                return ResourceManager.GetString("btnMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WPF-Sample: Moving an external window ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client window cannot be moved. ähnelt.
        /// </summary>
        public static string fbClWndcnbM {
            get {
                return ResourceManager.GetString("fbClWndcnbM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client window no longer available. ähnelt.
        /// </summary>
        public static string fbClWndnla {
            get {
                return ResourceManager.GetString("fbClWndnla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exception occured: {0} ähnelt.
        /// </summary>
        public static string fbExceptionOcc {
            get {
                return ResourceManager.GetString("fbExceptionOcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Found target. ähnelt.
        /// </summary>
        public static string fbFoundTarget {
            get {
                return ResourceManager.GetString("fbFoundTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No target. ähnelt.
        /// </summary>
        public static string fbNoTarget {
            get {
                return ResourceManager.GetString("fbNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object not responding in a timely manner. ähnelt.
        /// </summary>
        public static string fbObjNotResponding {
            get {
                return ResourceManager.GetString("fbObjNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object does not support the {0} Pattern. ähnelt.
        /// </summary>
        public static string fbObjNotSupPattern {
            get {
                return ResourceManager.GetString("fbObjNotSupPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object supports the {0} Pattern. ähnelt.
        /// </summary>
        public static string fbObjSupPattern {
            get {
                return ResourceManager.GetString("fbObjSupPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Window ready for user interaction ähnelt.
        /// </summary>
        public static string fbWinRdyIntact {
            get {
                return ResourceManager.GetString("fbWinRdyIntact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Window is not moveable. ähnelt.
        /// </summary>
        public static string fbWndNotMbl {
            get {
                return ResourceManager.GetString("fbWndNotMbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alert: Final {0}-coordinate not equal to requested {0}-coordinate. ähnelt.
        /// </summary>
        public static string fdKoorEqualtoReq {
            get {
                return ResourceManager.GetString("fdKoorEqualtoReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}-coordinate would place the window all or partially off-screen. ähnelt.
        /// </summary>
        public static string fdKWouldWinOffscreen {
            get {
                return ResourceManager.GetString("fdKWouldWinOffscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Window moved from {0} to {1} ähnelt.
        /// </summary>
        public static string fdWinMovedto {
            get {
                return ResourceManager.GetString("fdWinMovedto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die using CommunityToolkit.Mvvm.ComponentModel;
        ///using CommunityToolkit.Mvvm.Input;
        ///using MVVM.ViewModel;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Collections.ObjectModel;
        ///using System.ComponentModel;
        ///using System.Diagnostics;
        ///using System.Globalization;
        ///using System.Linq;
        ///using System.Security.Permissions;
        ///using System.Text;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///using System.Windows;
        ///using System.Windows.Automation;
        ///using System.Windows.Threading;
        ///using WPF_M [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string MoveWindowModel {
            get {
                return ResourceManager.GetString("MoveWindowModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Page
        ///      xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///      xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///      xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///      xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///      xmlns:local=&quot;clr-namespace:WPF_MoveWindow.Views&quot;
        ///      xmlns:p=&quot;clr-namespace:WPF_MoveWindow.Properties&quot;
        ///      xmlns:mvvm=&quot;clr-namespace:WPF_MoveWindow.ViewModels&quot;
        ///    x:Class=&quot;WPF_MoveWindow.Views.MoveWindowView&quot; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string MoveWindowView {
            get {
                return ResourceManager.GetString("MoveWindowView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notepad.exe ähnelt.
        /// </summary>
        public static string TargetApplication {
            get {
                return ResourceManager.GetString("TargetApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WPF-Move-Window ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X-coordiante: ähnelt.
        /// </summary>
        public static string txtXKoor {
            get {
                return ResourceManager.GetString("txtXKoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Y-coordinate: ähnelt.
        /// </summary>
        public static string txtYKoor {
            get {
                return ResourceManager.GetString("txtYKoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die // ***********************************************************************
        ///// Assembly         : WPF_MoveWindow
        ///// Author           : Mir
        ///// Created          : 08-11-2022
        /////
        ///// Last Modified By : Mir
        ///// Last Modified On : 08-24-2022
        ///// ***********************************************************************
        ///// &lt;copyright file=&quot;MoveWindowViewModel.cs&quot; company=&quot;JC-Soft&quot;&gt;
        /////     Copyright © JC-Soft 2022
        ///// &lt;/copyright&gt;
        ///// &lt;summary&gt;&lt;/summary&gt;
        ///// ******************************************************* [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string WindowMoveViewModel {
            get {
                return ResourceManager.GetString("MoveWindowViewModel", resourceCulture);
            }
        }
    }
}
