// ***********************************************************************
// Assembly         : Snake_Base
// Author           : Mir
// Created          : 08-26-2022
//
// Last Modified By : Mir
// Last Modified On : 09-09-2022
// ***********************************************************************
// <copyright file="TileDef.cs" company="JC-Soft">
//     Copyright (c) JC-Soft. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using ConsoleDisplay.View;
using System.Drawing;

/// <summary>
/// The View namespace.
/// </summary>
/// <autogeneratedoc />
namespace Snake_Console.View;

/// <summary>
/// Class TileDef.
/// Implements the <see cref="TileDef{Tiles}" /></summary>
/// <seealso cref="TileDef{Tiles}" />
public class TileDef : TileDefBase
{
    /// <summary>
    /// The v tile definition string
    /// </summary>
    /// <autogeneratedoc />
    private string[][] _vTileDefStr = [
        ["  "], //Empty
        ["|_"], //Wall
        ["##"], //Apple
        ["/\\"], //Head_N
        ["''"], //Tail_N
        ["||"], //Boby_NS
        ["<}"], //Head_W
        ["\\/"], //Head_S
        ["{>"], //Head_E
        ["=-"], //Tail_W
        [",,"], //Tail_S
        ["-="], //Tail_E
        ["++"], 
        ["++"],
        ["++"],
        ["++"],
        ["=="], //Body_WE
    ];

    /// <summary>
    /// The v tile colors
    /// </summary>
    /// <autogeneratedoc />
    private byte[][] _vTileColors = [
        [0x07], //Empty
			[0x4F], //Wall
        [0x0C], //Apple
        [0xAE], //Head_N
        [0x0E], 
        [0x0E],
        [0xAE],
        [0xAE],
        [0xAE],
        [0x0E] //Rest ...
    ];

    /// <summary>
    /// Gets the tile definition.
    /// </summary>
    /// <param name="tile">The tile.</param>
    /// <returns>(string[] lines, (System.ConsoleColor fgr, System.ConsoleColor bgr)[] colors).</returns>
    /// <autogeneratedoc />
    public override (string[] lines, (ConsoleColor fgr, ConsoleColor bgr)[] colors) GetTileDef(Enum? tile)
    {
        (string[] lines, (ConsoleColor fgr, ConsoleColor bgr)[] colors) result = default;
        result.lines = GetArrayElement(_vTileDefStr, tile);

        result.colors = new (ConsoleColor fgr, ConsoleColor bgr)[result.lines.Length * result.lines[0].Length];
        byte[] colDef = GetArrayElement(_vTileColors, tile);
        for (var i = 0; i < result.lines.Length * result.lines[0].Length; i++)
            result.colors[i] = ByteTo2ConsColor(colDef[i % colDef.Length]);
        return result;
    }

    public TileDef():base() {
        TileSize = new Size(2, 1);
    }
}
