// ***********************************************************************
// Assembly         : Calc32WPFTests
// Author           : Mir
// Created          : 12-23-2021
//
// Last Modified By : Mir
// Last Modified On : 08-28-2022
// ***********************************************************************
// <copyright file="MainWindowViewModelTests.cs" company="JC-Soft">
//     Copyright © JC-Soft 2021
// </copyright>
// <summary></summary>
// ***********************************************************************
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.ComponentModel;

/// <summary>
/// The Tests namespace.
/// </summary>
/// <autogeneratedoc />
namespace Calc32WPF.ViewModel.Tests
{
    /// <summary>
    /// Defines test class MainWindowViewModelTests.
    /// </summary>
    /// <autogeneratedoc />
    [TestClass()]
    public class MainWindowViewModelTests
    {
        /// <summary>
        /// The property changed count
        /// </summary>
        /// <autogeneratedoc />
        private int _PropChangedCount;
        /// <summary>
        /// The property changed
        /// </summary>
        /// <autogeneratedoc />
        private string _PropChanged = "";
        /// <summary>
        /// The model view
        /// </summary>
        /// <autogeneratedoc />
        private MainWindowViewModel _ModelView;

        /// <summary>
        /// Tests the initialize.
        /// </summary>
        /// <autogeneratedoc />
        [TestInitialize]
        public void TestInitialize()
        {
            ClearResults();
            _ModelView = new MainWindowViewModel();
            _ModelView.PropertyChanged += MainWindow_VM_PropChanged;
        }

        private void ClearResults()
        {
            _PropChangedCount = 0;
            _PropChanged = "";
        }

        /// <summary>
        /// Handles the PropChanged event of the MainWindow_VM control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="PropertyChangedEventArgs"/> instance containing the event data.</param>
        /// <autogeneratedoc />
        private void MainWindow_VM_PropChanged(object sender, PropertyChangedEventArgs e)
        {
            _PropChangedCount++;
            _PropChanged += $"{e.PropertyName}\r\n";
        }

        /// <summary>
        /// Defines the test method MainWindowViewModelTestSetup.
        /// </summary>
        /// <autogeneratedoc />
        [TestMethod()]
        public void MainWindowViewModelTestSetup()
        {
            Assert.IsNotNull(_ModelView);
            Assert.AreEqual(0, _PropChangedCount);
        }

        /// <summary>
        /// Mains the window vm number button.
        /// </summary>
        /// <param name="sButtons">The s buttons.</param>
        /// <param name="iPCCount">The i pc count.</param>
        /// <param name="sAkk">The s akk.</param>
        /// <autogeneratedoc />
        [DataTestMethod()]
        [DataRow("0", 0, 0, "")]
        [DataRow("1", 3, 1, "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("2", 3, 2, "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("3", 3, 3, "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("4", 3, 4, "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("5", 3, 5, "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("6", 3, 6, "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("7", 3, 7, "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("8", 3, 8, "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("9", 3, 9, "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("00", 0, 0, "")]
        [DataRow("01", 3, 1, "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("10", 6, 10, "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        public void MainWindow_VM_NumButton(string sButtons, int iPCCount, int sAkk, string sExpPC)
        {
            foreach (var button in sButtons)
            {
                if (button >= '0' && button <= '9')
                    _ModelView.btnNumber.Execute($"{button}");

            }
            Assert.AreEqual(iPCCount, _PropChangedCount);
            Assert.AreEqual(sAkk, _ModelView.Akkumulator);
            Assert.AreEqual(sExpPC, _PropChanged);

        }

        [DataTestMethod()]
        [DataRow("0",100, 0, 100, "", "")]
        [DataRow("0", 0, 0, 0, "", "")]
        [DataRow("0", -1, 0, -1, "", "")]
        [DataRow("0", int.MaxValue, 0, int.MaxValue, "", "")]
        [DataRow("0", int.MinValue, 0, int.MinValue, "", "")]
        [DataRow("1", 100, 0, 100, "=", "")]
        [DataRow("1", 0, 0, 0, "=", "")]
        [DataRow("1", -1, 0, -1, "=", "")]
        [DataRow("1", int.MaxValue, 0, int.MaxValue, "=", "")]
        [DataRow("1", int.MinValue, 0, int.MinValue, "=", "")]
        [DataRow("2", 100, 3, 100, "+", "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("21", 100, 6, 200, "=", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("22", 100, 6, 200, "+", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("3", 100, 3, 100, "-", "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("31", 100, 6, 0, "=", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("311", 100, 6, 0, "=", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("33", 100, 6, 0, "-", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("4", 100, 3, 100, "*", "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("41", 100, 6, 10000, "=", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("44", 100, 6, 10000, "*", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("5", 100, 3, 100, "/", "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("51", 100, 6, 1, "=", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("55", 100, 6, 1, "/", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("6", 100, 3, 100, "&", "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("61", 100, 6, 100, "=", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("66", 100, 3, 100, "&", "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("7", 100, 3, 100, "|", "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("71", 100, 6, 100, "=", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("77", 100, 3, 100, "|", "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("8", 100, 3, 100, "x", "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("81", 100, 6, 0, "=", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("88", 100, 6, 0, "x", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("9", 100, 3, -101, "", "Akkumulator\r\nMemory\r\nOperationText\r\n")]
        [DataRow("99", 100, 6, 100, "", "Akkumulator\r\nMemory\r\nOperationText\r\nAkkumulator\r\nMemory\r\nOperationText\r\n")]
        public void MainWindow_VM_OpButton(string sButtons, int iAcc,  int iPCCount, int iExpAkk,string sExpOp , string sExpPC)
        {
            _ModelView.Akkumulator = iAcc;
            ClearResults();    
            foreach (var button in sButtons)
            {
                if (button >= '0' && button <= '9')
                    _ModelView.btnOperation.Execute($"-{button}");

            }
            Assert.AreEqual(iPCCount, _PropChangedCount,$"Test: {sButtons}.PCCount");
            Assert.AreEqual(iExpAkk, _ModelView.Akkumulator, $"Test: {sButtons}.Acc");
            Assert.AreEqual(sExpOp, _ModelView.OperationText, $"Test: {sButtons}.Op");
            Assert.AreEqual(sExpPC, _PropChanged, $"Test: {sButtons}.PropChanges");
        }
    }
}