using BaseLib.Helper;
using GenFreeWin.Data;
using GenFreeWin.Main;
using GenFree.Helper;
//using DAO;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Windows.Forms;

namespace GenFreeWin.Views;

internal partial class Fehlerli
{
    private IContainer components;

    [DebuggerNonUserCode]
    protected override void Dispose(bool Disposing)
    {
        if (Disposing && components != null)
        {
            components.Dispose();
        }
        base.Dispose(Disposing);
    }

    public ToolTip ToolTip1;

 
#pragma warning disable CS0618 // Typ oder Element ist veraltet
    [AccessedThroughProperty(nameof(Command1))]
    private ControlArray<Button> _Command1;
#pragma warning restore CS0618 // Typ oder Element ist veraltet

    //[AccessedThroughProperty(nameof(btnReqHint))]
    //private Button btnMainmenue;

    //[AccessedThroughProperty(nameof(btnRegisterSearch))]
    //private Button btnBack;

    //[AccessedThroughProperty(nameof(btnDuplBttn3))]
    //private Button btnShowUsage;

    //[AccessedThroughProperty(nameof(btnMoveToCause))]
    //private Button btnNextEntry;

    //[AccessedThroughProperty(nameof(btnChangeSexToM))]
    //private Button btnPrevEntry;

    //[AccessedThroughProperty(nameof(btnChangeSexToF))]
    //private Button btnSearch;

    //[AccessedThroughProperty(nameof(btnMoveToChurchCemet))]
    //private Button btnEnterNew2;

    //[AccessedThroughProperty(nameof(btnMoveToEntityAnot))]
    //private Button btnSearchName;

    //[AccessedThroughProperty(nameof(btnMoveToLowerDateAnot))]
    //private Button btnSearchNumber;

    //[AccessedThroughProperty(nameof(btnDeleteEntry))]
    //private Button _Button10;

    //[AccessedThroughProperty(nameof(btnMoveToDateAnot))]
    //private Button _Button11;

    //[AccessedThroughProperty(nameof(Button12))]
    //private Button _Button12;

    //[AccessedThroughProperty(nameof(Button13))]
    //private Button _Button13;

    //[AccessedThroughProperty(nameof(Button14))]
    //private Button _Button14;

    //[AccessedThroughProperty(nameof(Button17))]
    //private Button _Button17;
    //[AccessedThroughProperty(nameof(Button15))]
    //private Button _Button15;

    /*
       List2.DoubleClick += new EventHandler(List2_DoubleClick);
       List1.DoubleClick += new EventHandler(List1_DoubleClick);
       btnReqHint.Click += new EventHandler(btnShowAsocPeople_Click);
       btnRegisterSearch.Click += new EventHandler(btnNewEntry_Click);
       btnDuplBttn3.Click += new EventHandler(btnReenter_Click);
       btnMoveToCause.Click += new EventHandler(btnMoveToCause_Click);
       btnChangeSexToM.Click += new EventHandler(btnChangeSexToM_Click);
       btnChangeSexToF.Click += new EventHandler(btnChangeSexToF_Click);
       btnMoveToChurchCemet.Click += new EventHandler(btnMoveToChurchCemet_Click);
       btnMoveToEntityAnot.Click += new EventHandler(btnMoveToEntityAnot_Click);
       btnMoveToLowerDateAnot.Click += new EventHandler(btnMoveToLowerDateAnot_Click);
       btnDeleteEntry.Click += new EventHandler(btnMoveToLowerDateAnot_Click);
       btnMoveToDateAnot.Click += new EventHandler(OpenCalculations);
       Button12.Click += new EventHandler(OpenFunctionKeys);
       Button13.Click += new EventHandler(OpenConfig);
       Button14.Click += new EventHandler(OpenCheckFamilies);
       Button17.Click += new EventHandler(OpenDuplettes);
       Button15.Click += new EventHandler(OpenCheckMissing);

        */
    public ListBox List2;
    public Button _Command1_7;
    public Button _Command1_6;
    public Button _Command1_5;
    public Button _Command1_4;
    public Button _Command1_3;
    public Button _Command1_2;
    public ListBox List1;
    public Button _Command1_1;
    public Button _Command1_0;
    public Label _Label1_8;
    public Label _Label1_9;
    public Label _Label1_10;
    public Label _Label1_2;
    public Label _Label1_1;
    public Label _Label1_0;
    public Button Button1;
    public Button Button2;
    internal Label Label2;
    internal ProgressBar ProgressBar1;
    internal RadioButton RadioButton1;
    internal RadioButton RadioButton2;
    internal Label Label3;
    internal Label Label4;
    public Button Button3;
    public Button Button4;
    internal GroupBox GroupBox1;
    internal CheckBox CheckBox4;
    internal CheckBox CheckBox3;
    internal CheckBox CheckBox2;
    internal CheckBox CheckBox1;
    public Button Button5;
    internal GroupBox GroupBox2;
    internal GroupBox GroupBox3;
    internal CheckBox CheckBox13;
    internal CheckBox CheckBox12;
    internal CheckBox CheckBox11;
    internal CheckBox CheckBox10;
    internal CheckBox CheckBox9;
    internal CheckBox CheckBox8;
    internal CheckBox CheckBox7;
    internal CheckBox CheckBox6;
    internal CheckBox CheckBox5;
    internal GroupBox GroupBox4;
    internal CheckBox CheckBox15;
    internal CheckBox CheckBox16;
    internal CheckBox CheckBox17;
    internal CheckBox CheckBox18;
    internal CheckBox CheckBox19;
    internal CheckBox CheckBox20;
    internal CheckBox CheckBox21;
    internal CheckBox CheckBox22;
    public Button Button6;
    public Button Button7;
    public Button Button8;
    public Button Button9;
    public Button Button10;
    public Button Button11;
    public Button Button12;
    public Button Button13;
    public Button Button14;

    public Button Button17;
    internal GroupBox GroupBox8;
    internal RadioButton RadioButton9;
    internal Label Label6;
    internal GroupBox GroupBox10;
    internal RadioButton RadioButton3;

    internal RadioButton RadioButton5;
    internal RadioButton RadioButton6;
    internal RadioButton RadioButton7;
    internal RadioButton RadioButton4;
    internal RadioButton RadioButton13;
    internal RadioButton RadioButton8;
    internal RadioButton RadioButton12;
    internal GroupBox GroupBox5;
    internal RadioButton RadioButton15;
    internal RadioButton RadioButton16;
    internal RadioButton RadioButton17;
    internal Label Label5;
    public Button Button15;
    internal RadioButton RadioButton10;

    [DebuggerStepThrough]
    private void InitializeComponent()
    {
        components = new Container();
        ToolTip1 = new ToolTip(components);
        _Command1_7 = new Button();
        List2 = new ListBox();
        _Command1_6 = new Button();
        _Command1_5 = new Button();
        _Command1_4 = new Button();
        _Command1_3 = new Button();
        _Command1_2 = new Button();
        List1 = new ListBox();
        _Command1_1 = new Button();
        _Command1_0 = new Button();
        _Label1_8 = new Label();
        _Label1_9 = new Label();
        _Label1_10 = new Label();
        _Label1_2 = new Label();
        _Label1_1 = new Label();
        _Label1_0 = new Label();
        Button1 = new Button();
        Button2 = new Button();
        Label2 = new Label();
        ProgressBar1 = new ProgressBar();
        RadioButton1 = new RadioButton();
        RadioButton2 = new RadioButton();
        Label3 = new Label();
        Label4 = new Label();
        Button3 = new Button();
        Button4 = new Button();
        GroupBox1 = new GroupBox();
        CheckBox4 = new CheckBox();
        CheckBox3 = new CheckBox();
        CheckBox2 = new CheckBox();
        CheckBox1 = new CheckBox();
        Button5 = new Button();
        GroupBox2 = new GroupBox();
        GroupBox4 = new GroupBox();
        CheckBox15 = new CheckBox();
        CheckBox16 = new CheckBox();
        CheckBox17 = new CheckBox();
        CheckBox18 = new CheckBox();
        CheckBox19 = new CheckBox();
        CheckBox20 = new CheckBox();
        CheckBox21 = new CheckBox();
        CheckBox22 = new CheckBox();
        GroupBox3 = new GroupBox();
        CheckBox13 = new CheckBox();
        CheckBox12 = new CheckBox();
        CheckBox11 = new CheckBox();
        CheckBox10 = new CheckBox();
        CheckBox9 = new CheckBox();
        CheckBox8 = new CheckBox();
        CheckBox7 = new CheckBox();
        CheckBox6 = new CheckBox();
        CheckBox5 = new CheckBox();
        Button8 = new Button();
        Button6 = new Button();
        Button7 = new Button();
        Button9 = new Button();
        Button10 = new Button();
        Button11 = new Button();
        Button12 = new Button();
        Button13 = new Button();
        Button14 = new Button();
        GroupBox8 = new GroupBox();
        Label6 = new Label();
        GroupBox5 = new GroupBox();
        RadioButton15 = new RadioButton();
        RadioButton16 = new RadioButton();
        RadioButton17 = new RadioButton();
        GroupBox10 = new GroupBox();
        RadioButton10 = new RadioButton();
        Label5 = new Label();
        RadioButton12 = new RadioButton();
        RadioButton13 = new RadioButton();
        RadioButton5 = new RadioButton();
        RadioButton8 = new RadioButton();
        RadioButton6 = new RadioButton();
        RadioButton7 = new RadioButton();
        RadioButton4 = new RadioButton();
        RadioButton3 = new RadioButton();
        RadioButton9 = new RadioButton();
        Button17 = new Button();
        Button15 = new Button();
        GroupBox1.SuspendLayout();
        GroupBox2.SuspendLayout();
        GroupBox4.SuspendLayout();
        GroupBox3.SuspendLayout();
        GroupBox8.SuspendLayout();
        GroupBox5.SuspendLayout();
        GroupBox10.SuspendLayout();
        SuspendLayout();
        _Command1_7.BackColor = SystemColors.Control;
        _Command1_7.Cursor = Cursors.Default;
        _Command1_7.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Command1_7.ForeColor = SystemColors.ControlText;
        _Command1_7.Location = new Point(625, 666);
        _Command1_7.Margin = new Padding(4);
        _Command1_7.Name = "_Command1_7";
        _Command1_7.RightToLeft = RightToLeft.No;
        _Command1_7.Size = new Size(136, 22);
        _Command1_7.TabIndex = 15;
        _Command1_7.Text = "Orte";
        _Command1_7.UseVisualStyleBackColor = false;
        List2.BackColor = SystemColors.Window;
        List2.Cursor = Cursors.Default;
        List2.Font = new Font("Courier New", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        List2.ForeColor = SystemColors.WindowText;
        List2.ItemHeight = 17;
        List2.Location = new Point(11, 128);
        List2.Margin = new Padding(4);
        List2.Name = "List2";
        List2.RightToLeft = RightToLeft.No;
        List2.Size = new Size(824, 378);
        List2.TabIndex = 14;
        List2.Visible = false;
        _Command1_6.BackColor = SystemColors.Control;
        _Command1_6.Cursor = Cursors.Default;
        _Command1_6.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Command1_6.ForeColor = SystemColors.ControlText;
        _Command1_6.Location = new Point(13, 578);
        _Command1_6.Margin = new Padding(4);
        _Command1_6.Name = "_Command1_6";
        _Command1_6.RightToLeft = RightToLeft.No;
        _Command1_6.Size = new Size(284, 22);
        _Command1_6.TabIndex = 13;
        _Command1_6.Text = "Unvollständig verknüpfte Personen ";
        _Command1_6.UseVisualStyleBackColor = false;
        _Command1_5.BackColor = SystemColors.Control;
        _Command1_5.Cursor = Cursors.Default;
        _Command1_5.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Command1_5.ForeColor = SystemColors.ControlText;
        _Command1_5.Location = new Point(13, 556);
        _Command1_5.Margin = new Padding(4);
        _Command1_5.Name = "_Command1_5";
        _Command1_5.RightToLeft = RightToLeft.No;
        _Command1_5.Size = new Size(284, 22);
        _Command1_5.TabIndex = 12;
        _Command1_5.Text = "Personen ohne Datum";
        _Command1_5.UseVisualStyleBackColor = false;
        _Command1_4.BackColor = SystemColors.Control;
        _Command1_4.Cursor = Cursors.Default;
        _Command1_4.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Command1_4.ForeColor = SystemColors.ControlText;
        _Command1_4.Location = new Point(305, 556);
        _Command1_4.Margin = new Padding(4);
        _Command1_4.Name = "_Command1_4";
        _Command1_4.RightToLeft = RightToLeft.No;
        _Command1_4.Size = new Size(284, 22);
        _Command1_4.TabIndex = 11;
        _Command1_4.Text = "Familien ohne Datum";
        _Command1_4.UseVisualStyleBackColor = false;
        _Command1_3.BackColor = SystemColors.Control;
        _Command1_3.Cursor = Cursors.Default;
        _Command1_3.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Command1_3.ForeColor = SystemColors.ControlText;
        _Command1_3.Location = new Point(830, 624);
        _Command1_3.Margin = new Padding(4);
        _Command1_3.Name = "_Command1_3";
        _Command1_3.RightToLeft = RightToLeft.No;
        _Command1_3.Size = new Size(129, 28);
        _Command1_3.TabIndex = 7;
        _Command1_3.Text = "Dru";
        _Command1_3.UseVisualStyleBackColor = false;
        _Command1_2.BackColor = SystemColors.Control;
        _Command1_2.Cursor = Cursors.Default;
        _Command1_2.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Command1_2.ForeColor = SystemColors.ControlText;
        _Command1_2.Location = new Point(830, 660);
        _Command1_2.Margin = new Padding(4);
        _Command1_2.Name = "_Command1_2";
        _Command1_2.RightToLeft = RightToLeft.No;
        _Command1_2.Size = new Size(191, 28);
        _Command1_2.TabIndex = 5;
        _Command1_2.Text = "Me";
        _Command1_2.UseVisualStyleBackColor = false;
        List1.BackColor = SystemColors.Window;
        List1.Cursor = Cursors.Default;
        List1.Font = new Font("Courier New", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        List1.ForeColor = SystemColors.WindowText;
        List1.ItemHeight = 17;
        List1.Location = new Point(11, 128);
        List1.Margin = new Padding(4);
        List1.Name = "List1";
        List1.RightToLeft = RightToLeft.No;
        List1.Size = new Size(826, 378);
        List1.TabIndex = 4;
        _Command1_1.BackColor = SystemColors.Control;
        _Command1_1.Cursor = Cursors.Default;
        _Command1_1.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Command1_1.ForeColor = SystemColors.ControlText;
        _Command1_1.Location = new Point(305, 534);
        _Command1_1.Margin = new Padding(4);
        _Command1_1.Name = "btnCancel";
        _Command1_1.RightToLeft = RightToLeft.No;
        _Command1_1.Size = new Size(284, 22);
        _Command1_1.TabIndex = 2;
        _Command1_1.Text = "Fam";
        _Command1_1.UseVisualStyleBackColor = false;
        _Command1_0.BackColor = SystemColors.Control;
        _Command1_0.Cursor = Cursors.Default;
        _Command1_0.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Command1_0.ForeColor = SystemColors.ControlText;
        _Command1_0.Location = new Point(13, 534);
        _Command1_0.Margin = new Padding(4);
        _Command1_0.Name = "btnVerify";
        _Command1_0.RightToLeft = RightToLeft.No;
        _Command1_0.Size = new Size(284, 22);
        _Command1_0.TabIndex = 1;
        _Command1_0.Text = "Pe";
        _Command1_0.UseVisualStyleBackColor = false;
        _Label1_8.BackColor = Color.Red;
        _Label1_8.Cursor = Cursors.Default;
        _Label1_8.Font = new Font("Arial", 8.5f, FontStyle.Bold, GraphicsUnit.Point, 0);
        _Label1_8.ForeColor = Color.Yellow;
        _Label1_8.Location = new Point(5, 44);
        _Label1_8.Margin = new Padding(4, 0, 4, 0);
        _Label1_8.Name = "_Label1_8";
        _Label1_8.RightToLeft = RightToLeft.No;
        _Label1_8.Size = new Size(1016, 19);
        _Label1_8.TabIndex = 10;
        _Label1_8.TextAlign = ContentAlignment.MiddleCenter;
        _Label1_9.BackColor = Color.Red;
        _Label1_9.Cursor = Cursors.Default;
        _Label1_9.Font = new Font("Arial", 8.5f, FontStyle.Bold, GraphicsUnit.Point, 0);
        _Label1_9.ForeColor = Color.Yellow;
        _Label1_9.Location = new Point(5, 22);
        _Label1_9.Margin = new Padding(4, 0, 4, 0);
        _Label1_9.Name = "_Label1_9";
        _Label1_9.RightToLeft = RightToLeft.No;
        _Label1_9.Size = new Size(1016, 19);
        _Label1_9.TabIndex = 9;
        _Label1_9.TextAlign = ContentAlignment.MiddleCenter;
        _Label1_10.BackColor = Color.Red;
        _Label1_10.Cursor = Cursors.Default;
        _Label1_10.Font = new Font("Arial", 8.5f, FontStyle.Bold, GraphicsUnit.Point, 0);
        _Label1_10.ForeColor = Color.Yellow;
        _Label1_10.Location = new Point(5, 0);
        _Label1_10.Margin = new Padding(4, 0, 4, 0);
        _Label1_10.Name = "_Label1_10";
        _Label1_10.RightToLeft = RightToLeft.No;
        _Label1_10.Size = new Size(1016, 19);
        _Label1_10.TabIndex = 8;
        _Label1_10.TextAlign = ContentAlignment.MiddleCenter;
        _Label1_2.BackColor = SystemColors.Control;
        _Label1_2.Cursor = Cursors.Default;
        _Label1_2.Font = new Font("Courier New", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Label1_2.ForeColor = SystemColors.ControlText;
        _Label1_2.Location = new Point(5, 63);
        _Label1_2.Margin = new Padding(4, 0, 4, 0);
        _Label1_2.Name = "_Label1_2";
        _Label1_2.RightToLeft = RightToLeft.No;
        _Label1_2.Size = new Size(1016, 19);
        _Label1_2.TabIndex = 6;
        _Label1_2.TextAlign = ContentAlignment.TopCenter;
        _Label1_1.BackColor = SystemColors.Control;
        _Label1_1.Cursor = Cursors.Default;
        _Label1_1.Font = new Font("Courier New", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Label1_1.ForeColor = SystemColors.ControlText;
        _Label1_1.Location = new Point(5, 87);
        _Label1_1.Margin = new Padding(4, 0, 4, 0);
        _Label1_1.Name = "_Label1_1";
        _Label1_1.RightToLeft = RightToLeft.No;
        _Label1_1.Size = new Size(1016, 19);
        _Label1_1.TabIndex = 3;
        _Label1_0.BackColor = SystemColors.Control;
        _Label1_0.Cursor = Cursors.Default;
        _Label1_0.Font = new Font("Courier New", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        _Label1_0.ForeColor = SystemColors.ControlText;
        _Label1_0.Location = new Point(5, 105);
        _Label1_0.Margin = new Padding(4, 0, 4, 0);
        _Label1_0.Name = "_Label1_0";
        _Label1_0.RightToLeft = RightToLeft.No;
        _Label1_0.Size = new Size(1016, 19);
        _Label1_0.TabIndex = 0;
        Button1.BackColor = SystemColors.Control;
        Button1.Cursor = Cursors.Default;
        Button1.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button1.ForeColor = SystemColors.ControlText;
        Button1.Location = new Point(13, 622);
        Button1.Margin = new Padding(4);
        Button1.Name = "btnReqHint";
        Button1.RightToLeft = RightToLeft.No;
        Button1.Size = new Size(284, 22);
        Button1.TabIndex = 16;
        Button1.Text = "Personen ohne Eltern (tote Punkte) ";
        Button1.UseVisualStyleBackColor = false;
        Button2.BackColor = SystemColors.Control;
        Button2.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button2.Location = new Point(305, 600);
        Button2.Margin = new Padding(4);
        Button2.Name = "btnRegisterSearch";
        Button2.Size = new Size(284, 22);
        Button2.TabIndex = 17;
        Button2.Text = "unvollständige Familien\n(nur eine Person)";
        Button2.UseVisualStyleBackColor = false;
        Label2.AutoSize = true;
        Label2.Location = new Point(779, 782);
        Label2.Margin = new Padding(4, 0, 4, 0);
        Label2.Name = "lblState";
        Label2.Size = new Size(0, 17);
        Label2.TabIndex = 18;
        ProgressBar1.Location = new Point(6, 514);
        ProgressBar1.Margin = new Padding(4);
        ProgressBar1.Name = "ProgressBar1";
        ProgressBar1.Size = new Size(1000, 12);
        ProgressBar1.TabIndex = 19;
        RadioButton1.AutoSize = true;
        RadioButton1.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        RadioButton1.Location = new Point(884, 567);
        RadioButton1.Margin = new Padding(4);
        RadioButton1.Name = "RadioButton1";
        RadioButton1.Size = new Size(103, 21);
        RadioButton1.TabIndex = 20;
        RadioButton1.TabStop = true;
        RadioButton1.Text = "Nach Name";
        RadioButton1.UseVisualStyleBackColor = true;
        RadioButton2.AutoSize = true;
        RadioButton2.Checked = true;
        RadioButton2.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        RadioButton2.Location = new Point(884, 595);
        RadioButton2.Margin = new Padding(4);
        RadioButton2.Name = "RadioButton2";
        RadioButton2.Size = new Size(121, 21);
        RadioButton2.TabIndex = 21;
        RadioButton2.TabStop = true;
        RadioButton2.Text = "Nach Nummer";
        RadioButton2.UseVisualStyleBackColor = true;
        Label3.Font = new Font("Arial", 8.5f, FontStyle.Bold, GraphicsUnit.Point, 0);
        Label3.Location = new Point(859, 136);
        Label3.Margin = new Padding(4, 0, 4, 0);
        Label3.Name = "lblDisplayHint";
        Label3.Size = new Size(128, 203);
        Label3.TabIndex = 22;
        Label3.Text = "Achtung! \r\nDiese Listen sind statisch.\r\nNach ändern oder löschen von Einträgen ist ggf. ein neuer Suchlauf zu starten.\r\n";
        Label4.AutoSize = true;
        Label4.Location = new Point(837, 539);
        Label4.Name = "lblSearch";
        Label4.Size = new Size(0, 17);
        Label4.TabIndex = 23;
        Button3.BackColor = SystemColors.Control;
        Button3.Cursor = Cursors.Default;
        Button3.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button3.ForeColor = SystemColors.ControlText;
        Button3.Location = new Point(13, 644);
        Button3.Margin = new Padding(4);
        Button3.Name = "btnReenter";
        Button3.RightToLeft = RightToLeft.No;
        Button3.Size = new Size(284, 22);
        Button3.TabIndex = 24;
        Button3.Text = "Personen ohne konf. oder Sex = U";
        Button3.UseVisualStyleBackColor = false;
        Button4.BackColor = SystemColors.Control;
        Button4.Cursor = Cursors.Default;
        Button4.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button4.ForeColor = SystemColors.ControlText;
        Button4.Location = new Point(305, 578);
        Button4.Margin = new Padding(4);
        Button4.Name = "btnClose";
        Button4.RightToLeft = RightToLeft.No;
        Button4.Size = new Size(284, 22);
        Button4.TabIndex = 25;
        Button4.Text = "Familien mit unvollständigem Datum";
        Button4.UseVisualStyleBackColor = false;
        GroupBox1.Controls.Add(CheckBox4);
        GroupBox1.Controls.Add(CheckBox3);
        GroupBox1.Controls.Add(CheckBox2);
        GroupBox1.Controls.Add(CheckBox1);
        GroupBox1.Location = new Point(320, 23);
        GroupBox1.Name = "grpFather";
        GroupBox1.Size = new Size(172, 163);
        GroupBox1.TabIndex = 26;
        GroupBox1.TabStop = false;
        GroupBox1.Text = "prüfen auf";
        CheckBox4.AutoSize = true;
        CheckBox4.Location = new Point(11, 103);
        CheckBox4.Name = "CheckBox4";
        CheckBox4.Size = new Size(69, 21);
        CheckBox4.TabIndex = 3;
        CheckBox4.Text = "Quelle";
        CheckBox4.UseVisualStyleBackColor = true;
        CheckBox3.AutoSize = true;
        CheckBox3.Location = new Point(11, 76);
        CheckBox3.Name = "CheckBox3";
        CheckBox3.Size = new Size(112, 21);
        CheckBox3.TabIndex = 2;
        CheckBox3.Text = "Urkunden-Nr.";
        CheckBox3.UseVisualStyleBackColor = true;
        CheckBox2.AutoSize = true;
        CheckBox2.Location = new Point(11, 49);
        CheckBox2.Name = "CheckBox2";
        CheckBox2.Size = new Size(48, 21);
        CheckBox2.TabIndex = 1;
        CheckBox2.Text = "Ort";
        CheckBox2.UseVisualStyleBackColor = true;
        CheckBox1.AutoSize = true;
        CheckBox1.Location = new Point(11, 22);
        CheckBox1.Name = "cbxIllegitRel";
        CheckBox1.Size = new Size(159, 21);
        CheckBox1.TabIndex = 0;
        CheckBox1.Text = "vollständiges Datum";
        CheckBox1.UseVisualStyleBackColor = true;
        Button5.BackColor = Color.Lime;
        Button5.Location = new Point(354, 235);
        Button5.Name = "btnHometown";
        Button5.Size = new Size(75, 23);
        Button5.TabIndex = 4;
        Button5.Text = "Start";
        Button5.UseVisualStyleBackColor = false;
        GroupBox2.BackColor = Color.FromArgb(224, 224, 224);
        GroupBox2.Controls.Add(GroupBox4);
        GroupBox2.Controls.Add(GroupBox3);
        GroupBox2.Controls.Add(Button8);
        GroupBox2.Controls.Add(Button5);
        GroupBox2.Controls.Add(GroupBox1);
        GroupBox2.Location = new Point(222, 192);
        GroupBox2.Name = "GroupBox2";
        GroupBox2.Size = new Size(520, 275);
        GroupBox2.TabIndex = 27;
        GroupBox2.TabStop = false;
        GroupBox2.Visible = false;
        GroupBox4.Controls.Add(CheckBox15);
        GroupBox4.Controls.Add(CheckBox16);
        GroupBox4.Controls.Add(CheckBox17);
        GroupBox4.Controls.Add(CheckBox18);
        GroupBox4.Controls.Add(CheckBox19);
        GroupBox4.Controls.Add(CheckBox20);
        GroupBox4.Controls.Add(CheckBox21);
        GroupBox4.Controls.Add(CheckBox22);
        GroupBox4.Location = new Point(180, 23);
        GroupBox4.Name = "GroupBox4";
        GroupBox4.Size = new Size(134, 191);
        GroupBox4.TabIndex = 28;
        GroupBox4.TabStop = false;
        GroupBox4.Text = "Ereignis Person";
        CheckBox15.AutoSize = true;
        CheckBox15.Location = new Point(6, 170);
        CheckBox15.Name = "CheckBox15";
        CheckBox15.Size = new Size(115, 21);
        CheckBox15.TabIndex = 7;
        CheckBox15.Text = "sonst. Datum";
        CheckBox15.UseVisualStyleBackColor = true;
        CheckBox16.AutoSize = true;
        CheckBox16.Location = new Point(6, 149);
        CheckBox16.Name = "CheckBox16";
        CheckBox16.Size = new Size(83, 21);
        CheckBox16.TabIndex = 6;
        CheckBox16.Text = "Wohnort";
        CheckBox16.UseVisualStyleBackColor = true;
        CheckBox17.AutoSize = true;
        CheckBox17.Location = new Point(6, 128);
        CheckBox17.Name = "CheckBox17";
        CheckBox17.Size = new Size(53, 21);
        CheckBox17.TabIndex = 5;
        CheckBox17.Text = "Titel";
        CheckBox17.UseVisualStyleBackColor = true;
        CheckBox18.AutoSize = true;
        CheckBox18.Location = new Point(6, 107);
        CheckBox18.Name = "CheckBox18";
        CheckBox18.Size = new Size(62, 21);
        CheckBox18.TabIndex = 4;
        CheckBox18.Text = "Beruf";
        CheckBox18.UseVisualStyleBackColor = true;
        CheckBox19.AutoSize = true;
        CheckBox19.Location = new Point(6, 86);
        CheckBox19.Name = "CheckBox19";
        CheckBox19.Size = new Size(90, 21);
        CheckBox19.TabIndex = 3;
        CheckBox19.Text = "Begraben";
        CheckBox19.UseVisualStyleBackColor = true;
        CheckBox20.AutoSize = true;
        CheckBox20.Location = new Point(6, 65);
        CheckBox20.Name = "CheckBox20";
        CheckBox20.Size = new Size(46, 21);
        CheckBox20.TabIndex = 2;
        CheckBox20.Text = "Tot";
        CheckBox20.UseVisualStyleBackColor = true;
        CheckBox21.AutoSize = true;
        CheckBox21.Location = new Point(6, 44);
        CheckBox21.Name = "CheckBox21";
        CheckBox21.Size = new Size(62, 21);
        CheckBox21.TabIndex = 1;
        CheckBox21.Text = "Taufe";
        CheckBox21.UseVisualStyleBackColor = true;
        CheckBox22.AutoSize = true;
        CheckBox22.Location = new Point(6, 23);
        CheckBox22.Name = "CheckBox22";
        CheckBox22.Size = new Size(71, 21);
        CheckBox22.TabIndex = 0;
        CheckBox22.Text = "Geburt";
        CheckBox22.UseVisualStyleBackColor = true;
        GroupBox3.Controls.Add(CheckBox13);
        GroupBox3.Controls.Add(CheckBox12);
        GroupBox3.Controls.Add(CheckBox11);
        GroupBox3.Controls.Add(CheckBox10);
        GroupBox3.Controls.Add(CheckBox9);
        GroupBox3.Controls.Add(CheckBox8);
        GroupBox3.Controls.Add(CheckBox7);
        GroupBox3.Controls.Add(CheckBox6);
        GroupBox3.Controls.Add(CheckBox5);
        GroupBox3.Location = new Point(6, 23);
        GroupBox3.Name = "grpMother";
        GroupBox3.Size = new Size(168, 191);
        GroupBox3.TabIndex = 27;
        GroupBox3.TabStop = false;
        GroupBox3.Text = "Ereignis Familie";
        CheckBox13.AutoSize = true;
        CheckBox13.Location = new Point(6, 191);
        CheckBox13.Name = "CheckBox13";
        CheckBox13.Size = new Size(115, 21);
        CheckBox13.TabIndex = 8;
        CheckBox13.Text = "sonst. Datum";
        CheckBox13.UseVisualStyleBackColor = true;
        CheckBox13.Visible = false;
        CheckBox12.AutoSize = true;
        CheckBox12.Location = new Point(6, 170);
        CheckBox12.Name = "CheckBox12";
        CheckBox12.Size = new Size(91, 21);
        CheckBox12.TabIndex = 7;
        CheckBox12.Text = "Wohnorte";
        CheckBox12.UseVisualStyleBackColor = true;
        CheckBox12.Visible = false;
        CheckBox11.AutoSize = true;
        CheckBox11.Location = new Point(6, 149);
        CheckBox11.Name = "CheckBox11";
        CheckBox11.Size = new Size(108, 21);
        CheckBox11.TabIndex = 6;
        CheckBox11.Text = "Dimissiorale";
        CheckBox11.UseVisualStyleBackColor = true;
        CheckBox10.AutoSize = true;
        CheckBox10.Location = new Point(6, 128);
        CheckBox10.Name = "CheckBox10";
        CheckBox10.Size = new Size(157, 21);
        CheckBox10.TabIndex = 5;
        CheckBox10.Text = "Eheähnl. Beziehung";
        CheckBox10.UseVisualStyleBackColor = true;
        CheckBox9.AutoSize = true;
        CheckBox9.Location = new Point(6, 107);
        CheckBox9.Name = "CheckBox9";
        CheckBox9.Size = new Size(96, 21);
        CheckBox9.TabIndex = 4;
        CheckBox9.Text = "Scheidung";
        CheckBox9.UseVisualStyleBackColor = true;
        CheckBox8.AutoSize = true;
        CheckBox8.Location = new Point(6, 86);
        CheckBox8.Name = "CheckBox8";
        CheckBox8.Size = new Size(107, 21);
        CheckBox8.TabIndex = 3;
        CheckBox8.Text = "kirchl. Heirat";
        CheckBox8.UseVisualStyleBackColor = true;
        CheckBox7.AutoSize = true;
        CheckBox7.Location = new Point(6, 65);
        CheckBox7.Name = "CheckBox7";
        CheckBox7.Size = new Size(65, 21);
        CheckBox7.TabIndex = 2;
        CheckBox7.Text = "Heirat";
        CheckBox7.UseVisualStyleBackColor = true;
        CheckBox6.AutoSize = true;
        CheckBox6.Location = new Point(6, 44);
        CheckBox6.Name = "CheckBox6";
        CheckBox6.Size = new Size(112, 21);
        CheckBox6.TabIndex = 1;
        CheckBox6.Text = "Proklamation";
        CheckBox6.UseVisualStyleBackColor = true;
        CheckBox5.AutoSize = true;
        CheckBox5.Location = new Point(6, 23);
        CheckBox5.Name = "CheckBox5";
        CheckBox5.Size = new Size(91, 21);
        CheckBox5.TabIndex = 0;
        CheckBox5.Text = "Verlobung";
        CheckBox5.UseVisualStyleBackColor = true;
        Button8.BackColor = Color.Lime;
        Button8.Location = new Point(354, 235);
        Button8.Name = "btnCancel";
        Button8.Size = new Size(75, 23);
        Button8.TabIndex = 29;
        Button8.Text = "Start";
        Button8.UseVisualStyleBackColor = false;
        Button6.BackColor = SystemColors.Control;
        Button6.Cursor = Cursors.Default;
        Button6.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button6.ForeColor = SystemColors.ControlText;
        Button6.Location = new Point(13, 666);
        Button6.Margin = new Padding(4);
        Button6.Name = "btnDeleteQuiet";
        Button6.RightToLeft = RightToLeft.No;
        Button6.Size = new Size(284, 22);
        Button6.TabIndex = 28;
        Button6.Text = "lebende Personen";
        Button6.UseVisualStyleBackColor = false;
        Button7.BackColor = SystemColors.Control;
        Button7.Cursor = Cursors.Default;
        Button7.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button7.ForeColor = SystemColors.ControlText;
        Button7.Location = new Point(13, 600);
        Button7.Margin = new Padding(4);
        Button7.Name = "btnProperty";
        Button7.RightToLeft = RightToLeft.No;
        Button7.Size = new Size(284, 22);
        Button7.TabIndex = 29;
        Button7.Text = "Personen mit unvollständigem Datum";
        Button7.UseVisualStyleBackColor = false;
        Button9.BackColor = SystemColors.Control;
        Button9.Cursor = Cursors.Default;
        Button9.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button9.ForeColor = SystemColors.ControlText;
        Button9.Location = new Point(13, 690);
        Button9.Margin = new Padding(4);
        Button9.Name = "btnSearchNumber";
        Button9.RightToLeft = RightToLeft.No;
        Button9.Size = new Size(212, 22);
        Button9.TabIndex = 30;
        Button9.Text = "Datum wenn mögl. ergänzen";
        Button9.UseVisualStyleBackColor = false;
        Button10.BackColor = SystemColors.Control;
        Button10.Cursor = Cursors.Default;
        Button10.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button10.ForeColor = SystemColors.ControlText;
        Button10.Location = new Point(228, 690);
        Button10.Margin = new Padding(4);
        Button10.Name = "Button10";
        Button10.RightToLeft = RightToLeft.No;
        Button10.Size = new Size(275, 22);
        Button10.TabIndex = 31;
        Button10.Text = "Personen ohne Datum für OFB sperren";
        Button10.UseVisualStyleBackColor = false;
        Button11.BackColor = SystemColors.Control;
        Button11.Cursor = Cursors.Default;
        Button11.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button11.ForeColor = SystemColors.ControlText;
        Button11.Location = new Point(783, 690);
        Button11.Margin = new Padding(4);
        Button11.Name = "btnEdit";
        Button11.RightToLeft = RightToLeft.No;
        Button11.Size = new Size(222, 22);
        Button11.TabIndex = 32;
        Button11.Text = "Für OFB gesperrte Personen";
        Button11.UseVisualStyleBackColor = false;
        Button12.BackColor = SystemColors.Control;
        Button12.Cursor = Cursors.Default;
        Button12.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button12.ForeColor = SystemColors.ControlText;
        Button12.Location = new Point(592, 534);
        Button12.Margin = new Padding(4);
        Button12.Name = "btnShowPlaces";
        Button12.RightToLeft = RightToLeft.No;
        Button12.Size = new Size(213, 22);
        Button12.TabIndex = 33;
        Button12.Text = "Liste Person ist Pate bei";
        Button12.UseVisualStyleBackColor = false;
        Button13.BackColor = SystemColors.Control;
        Button13.Cursor = Cursors.Default;
        Button13.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button13.ForeColor = SystemColors.ControlText;
        Button13.Location = new Point(592, 556);
        Button13.Margin = new Padding(4);
        Button13.Name = "btnSearchNumber2";
        Button13.RightToLeft = RightToLeft.No;
        Button13.Size = new Size(213, 22);
        Button13.TabIndex = 34;
        Button13.Text = "Liste Person ist Zeuge bei";
        Button13.UseVisualStyleBackColor = false;
        Button14.BackColor = SystemColors.Control;
        Button14.Cursor = Cursors.Default;
        Button14.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button14.ForeColor = SystemColors.ControlText;
        Button14.Location = new Point(592, 600);
        Button14.Margin = new Padding(4);
        Button14.Name = "btnResarch";
        Button14.RightToLeft = RightToLeft.No;
        Button14.Size = new Size(230, 22);
        Button14.TabIndex = 35;
        Button14.Text = "Sicherheitszusätze beim Datum";
        Button14.UseVisualStyleBackColor = false;
        GroupBox8.BackColor = Color.FromArgb(224, 224, 224);
        GroupBox8.Controls.Add(Label6);
        GroupBox8.Controls.Add(GroupBox5);
        GroupBox8.Controls.Add(GroupBox10);
        GroupBox8.Controls.Add(Button17);
        GroupBox8.Location = new Point(216, 164);
        GroupBox8.Name = "GroupBox8";
        GroupBox8.Size = new Size(520, 314);
        GroupBox8.TabIndex = 37;
        GroupBox8.TabStop = false;
        GroupBox8.Visible = false;
        Label6.Location = new Point(9, 14);
        Label6.Name = "Label6";
        Label6.Size = new Size(508, 29);
        Label6.TabIndex = 30;
        Label6.Text = "Listen der Datumzusätze";
        Label6.TextAlign = ContentAlignment.TopCenter;
        GroupBox5.BackColor = Color.FromArgb(255, 192, 128);
        GroupBox5.Controls.Add(RadioButton15);
        GroupBox5.Controls.Add(RadioButton16);
        GroupBox5.Controls.Add(RadioButton17);
        GroupBox5.Location = new Point(139, 241);
        GroupBox5.Name = "GroupBox5";
        GroupBox5.Size = new Size(185, 67);
        GroupBox5.TabIndex = 31;
        GroupBox5.TabStop = false;
        GroupBox5.Text = "Suchen bei";
        RadioButton15.AutoSize = true;
        RadioButton15.Location = new Point(6, 46);
        RadioButton15.Name = "RadioButton15";
        RadioButton15.Size = new Size(122, 21);
        RadioButton15.TabIndex = 42;
        RadioButton15.TabStop = true;
        RadioButton15.Text = "Familiendatum";
        RadioButton15.UseVisualStyleBackColor = true;
        RadioButton16.AutoSize = true;
        RadioButton16.Checked = true;
        RadioButton16.Location = new Point(6, 19);
        RadioButton16.Name = "RadioButton16";
        RadioButton16.Size = new Size(130, 21);
        RadioButton16.TabIndex = 41;
        RadioButton16.TabStop = true;
        RadioButton16.Text = "Personendatum";
        RadioButton16.UseVisualStyleBackColor = true;
        RadioButton17.AutoSize = true;
        RadioButton17.Location = new Point(182, 103);
        RadioButton17.Name = "RadioButton17";
        RadioButton17.Size = new Size(122, 21);
        RadioButton17.TabIndex = 38;
        RadioButton17.TabStop = true;
        RadioButton17.Text = "RadioButton17";
        RadioButton17.UseVisualStyleBackColor = true;
        GroupBox10.BackColor = Color.FromArgb(255, 192, 128);
        GroupBox10.Controls.Add(RadioButton10);
        GroupBox10.Controls.Add(Label5);
        GroupBox10.Controls.Add(RadioButton12);
        GroupBox10.Controls.Add(RadioButton13);
        GroupBox10.Controls.Add(RadioButton5);
        GroupBox10.Controls.Add(RadioButton8);
        GroupBox10.Controls.Add(RadioButton6);
        GroupBox10.Controls.Add(RadioButton7);
        GroupBox10.Controls.Add(RadioButton4);
        GroupBox10.Controls.Add(RadioButton3);
        GroupBox10.Controls.Add(RadioButton9);
        GroupBox10.Location = new Point(12, 45);
        GroupBox10.Name = "GroupBox10";
        GroupBox10.Size = new Size(373, 186);
        GroupBox10.TabIndex = 27;
        GroupBox10.TabStop = false;
        GroupBox10.Text = "Zusätze erstes Datum   Zusätze beide  Daten";
        RadioButton10.AutoSize = true;
        RadioButton10.Location = new Point(7, 148);
        RadioButton10.Name = "RadioButton10";
        RadioButton10.Size = new Size(92, 21);
        RadioButton10.TabIndex = 45;
        RadioButton10.TabStop = true;
        RadioButton10.Text = "Zusatz \"c\"";
        RadioButton10.UseVisualStyleBackColor = true;
        Label5.AutoSize = true;
        Label5.Location = new Point(185, 106);
        Label5.Name = "lblSorting";
        Label5.Size = new Size(164, 17);
        Label5.TabIndex = 44;
        Label5.Text = "Zusätze hinteres Datum";
        RadioButton12.AutoSize = true;
        RadioButton12.Location = new Point(7, 121);
        RadioButton12.Name = "RadioButton12";
        RadioButton12.Size = new Size(92, 21);
        RadioButton12.TabIndex = 43;
        RadioButton12.TabStop = true;
        RadioButton12.Text = "Zusatz \"z\"";
        RadioButton12.UseVisualStyleBackColor = true;
        RadioButton13.AutoSize = true;
        RadioButton13.Location = new Point(188, 157);
        RadioButton13.Name = "RadioButton13";
        RadioButton13.Size = new Size(92, 21);
        RadioButton13.TabIndex = 42;
        RadioButton13.TabStop = true;
        RadioButton13.Text = "Zusatz \"b\"";
        RadioButton13.UseVisualStyleBackColor = true;
        RadioButton5.AutoSize = true;
        RadioButton5.Location = new Point(7, 43);
        RadioButton5.Name = "RadioButton5";
        RadioButton5.Size = new Size(92, 21);
        RadioButton5.TabIndex = 41;
        RadioButton5.TabStop = true;
        RadioButton5.Text = "Zusatz \"n\"";
        RadioButton5.UseVisualStyleBackColor = true;
        RadioButton8.AutoSize = true;
        RadioButton8.Location = new Point(188, 130);
        RadioButton8.Name = "RadioButton8";
        RadioButton8.Size = new Size(92, 21);
        RadioButton8.TabIndex = 41;
        RadioButton8.TabStop = true;
        RadioButton8.Text = "Zusatz \"a\"";
        RadioButton8.UseVisualStyleBackColor = true;
        RadioButton6.AutoSize = true;
        RadioButton6.Location = new Point(6, 70);
        RadioButton6.Name = "RadioButton6";
        RadioButton6.Size = new Size(92, 21);
        RadioButton6.TabIndex = 42;
        RadioButton6.TabStop = true;
        RadioButton6.Text = "Zusatz \"u\"";
        RadioButton6.UseVisualStyleBackColor = true;
        RadioButton7.AutoSize = true;
        RadioButton7.Location = new Point(6, 94);
        RadioButton7.Name = "RadioButton7";
        RadioButton7.Size = new Size(89, 21);
        RadioButton7.TabIndex = 43;
        RadioButton7.TabStop = true;
        RadioButton7.Text = "Zusatz \"r\"";
        RadioButton7.UseVisualStyleBackColor = true;
        RadioButton4.Location = new Point(188, 16);
        RadioButton4.Name = "RadioButton4";
        RadioButton4.Size = new Size(163, 43);
        RadioButton4.TabIndex = 41;
        RadioButton4.TabStop = true;
        RadioButton4.Text = "Zusatz \"?\" (wegfallend)";
        RadioButton4.UseVisualStyleBackColor = true;
        RadioButton3.AutoSize = true;
        RadioButton3.Location = new Point(7, 20);
        RadioButton3.Name = "RadioButton3";
        RadioButton3.Size = new Size(91, 21);
        RadioButton3.TabIndex = 31;
        RadioButton3.TabStop = true;
        RadioButton3.Text = "Zusatz \"v\"";
        RadioButton3.UseVisualStyleBackColor = true;
        RadioButton9.Location = new Point(188, 55);
        RadioButton9.Name = "RadioButton9";
        RadioButton9.Size = new Size(163, 43);
        RadioButton9.TabIndex = 37;
        RadioButton9.TabStop = true;
        RadioButton9.Text = "sonstige Zusätze (unzulässig)";
        RadioButton9.UseVisualStyleBackColor = true;
        Button17.BackColor = Color.Lime;
        Button17.Location = new Point(441, 274);
        Button17.Name = "Button17";
        Button17.Size = new Size(75, 23);
        Button17.TabIndex = 29;
        Button17.Text = "Start";
        Button17.UseVisualStyleBackColor = false;
        Button15.BackColor = SystemColors.Control;
        Button15.Cursor = Cursors.Default;
        Button15.Font = new Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button15.ForeColor = SystemColors.ControlText;
        Button15.Location = new Point(511, 690);
        Button15.Margin = new Padding(4);
        Button15.Name = "btnChildren";
        Button15.RightToLeft = RightToLeft.No;
        Button15.Size = new Size(250, 22);
        Button15.TabIndex = 38;
        Button15.Text = "Sperrung allerPersonen aufheben";
        Button15.UseVisualStyleBackColor = false;
        AutoScaleDimensions = new SizeF(8f, 17f);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(255, 192, 192);
        ClientSize = new Size(1018, 725);
        ControlBox = false;
        List2.DoubleClick += new EventHandler(List2_DoubleClick);
        List1.DoubleClick += new EventHandler(List1_DoubleClick);
        Button1.Click += new EventHandler(Button1_Click);
        Button2.Click += new EventHandler(Button2_Click);
        Button3.Click += new EventHandler(Button3_Click);
        Button4.Click += new EventHandler(Button4_Click);
        Button5.Click += new EventHandler(Button5_Click);
        Button6.Click += new EventHandler(Button6_Click);
        Button7.Click += new EventHandler(Button7_Click);
        Button8.Click += new EventHandler(Button8_Click);
        Button9.Click += new EventHandler(Button9_Click);
        Button10.Click += new EventHandler(Button9_Click);
        Button11.Click += new EventHandler(Button11_Click);
        Button12.Click += new EventHandler(Button12_Click);
        Button13.Click += new EventHandler(Button13_Click);
        Button14.Click += new EventHandler(Button14_Click);
        Button17.Click += new EventHandler(Button17_Click);
        Button15.Click += new EventHandler(Button15_Click);

        Controls.Add(Button15);
        Controls.Add(GroupBox8);
        Controls.Add(Button14);
        Controls.Add(Button13);
        Controls.Add(Button12);
        Controls.Add(Button11);
        Controls.Add(Button10);
        Controls.Add(Button9);
        Controls.Add(Button7);
        Controls.Add(Button6);
        Controls.Add(GroupBox2);
        Controls.Add(Button4);
        Controls.Add(Button3);
        Controls.Add(Label4);
        Controls.Add(Label3);
        Controls.Add(RadioButton2);
        Controls.Add(RadioButton1);
        Controls.Add(ProgressBar1);
        Controls.Add(Label2);
        Controls.Add(Button2);
        Controls.Add(Button1);
        Controls.Add(_Command1_7);
        Controls.Add(List2);
        Controls.Add(_Command1_6);
        Controls.Add(_Command1_5);
        Controls.Add(_Command1_4);
        Controls.Add(_Command1_3);
        Controls.Add(_Command1_2);
        Controls.Add(List1);
        Controls.Add(_Command1_1);
        Controls.Add(_Command1_0);
        Controls.Add(_Label1_8);
        Controls.Add(_Label1_9);
        Controls.Add(_Label1_10);
        Controls.Add(_Label1_2);
        Controls.Add(_Label1_1);
        Controls.Add(_Label1_0);
        Cursor = Cursors.Default;
        Font = new Font("Arial", 11f);
        FormBorderStyle = FormBorderStyle.FixedSingle;
        Margin = new Padding(4);
        Name = "Fehlerli";
        RightToLeft = RightToLeft.No;
        SizeGripStyle = SizeGripStyle.Hide;
        StartPosition = FormStartPosition.Manual;
        Text = "Fehlliste";
        GroupBox1.ResumeLayout(false);
        GroupBox1.PerformLayout();
        GroupBox2.ResumeLayout(false);
        GroupBox4.ResumeLayout(false);
        GroupBox4.PerformLayout();
        GroupBox3.ResumeLayout(false);
        GroupBox3.PerformLayout();
        GroupBox8.ResumeLayout(false);
        GroupBox5.ResumeLayout(false);
        GroupBox5.PerformLayout();
        GroupBox10.ResumeLayout(false);
        GroupBox10.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }

}