using BaseLib.Helper;
using GenFreeWin.Main;
using GenFreeWin.Views;
using GenFree;
using GenFree.Data;
using GenFree.Helper;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Runtime.CompilerServices;
using System.Windows.Forms;
using System.ComponentModel;
using GenFree.Interfaces.Sys;
using GenFree.ViewModels.Interfaces;
using GenFreeWin.Views;

namespace GenFreeWin;

public partial class Quellen 
{
    // Felder statt Properties
    private Button Button1;
    public Button Button2;
    public Button Button3;
    private Button Button4;
    private Button Button5;
    public ComboBox ComboBox1;
    private TextBox TextBox1;
    private RadioButton Option2;
    private ListBox ListBox1;
    public RichTextBox RTB;
    private Button Button7;
    private TextBox TextBox2;
    private Button Button6;
    private Button Button8;
    private Button Button9;
    internal Label Label1;
    internal RadioButton Option1;
    internal Label Label3;
    internal Label Label2;
    internal Label Label4;

    // Eventhandler direkt im Konstruktor zuweisen
    [System.Diagnostics.DebuggerStepThrough]
    private void InitializeComponent()
    {
        Label1 = new System.Windows.Forms.Label();
        Button1 = new System.Windows.Forms.Button();
        Button2 = new System.Windows.Forms.Button();
        Button3 = new System.Windows.Forms.Button();
        Button4 = new System.Windows.Forms.Button();
        Button5 = new System.Windows.Forms.Button();
        ComboBox1 = new System.Windows.Forms.ComboBox();
        TextBox1 = new System.Windows.Forms.TextBox();
        RTB = new System.Windows.Forms.RichTextBox();
        Option1 = new System.Windows.Forms.RadioButton();
        Option2 = new System.Windows.Forms.RadioButton();
        ListBox1 = new System.Windows.Forms.ListBox();
        Button7 = new System.Windows.Forms.Button();
        Label3 = new System.Windows.Forms.Label();
        Label2 = new System.Windows.Forms.Label();
        Label4 = new System.Windows.Forms.Label();
        TextBox2 = new System.Windows.Forms.TextBox();
        Button6 = new System.Windows.Forms.Button();
        Button8 = new System.Windows.Forms.Button();
        Button9 = new System.Windows.Forms.Button();
        SuspendLayout();
        Label1.BackColor = Color.Yellow;
        Label1.Location = new System.Drawing.Point(0, -1);
        Label1.Name = "Label1";
        Label1.Size = new System.Drawing.Size(875, 20);
        Label1.TabIndex = 0;
        Label1.Text = "Quellen";
        Label1.TextAlign = ContentAlignment.MiddleCenter;
        Button1.BackColor = Color.FromArgb(224, 224, 224);
        Button1.Font = new System.Drawing.Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button1.Location = new System.Drawing.Point(3, 29);
        Button1.Name = "btnReqHint";
        Button1.Size = new System.Drawing.Size(122, 48);
        Button1.TabIndex = 1;
        Button1.Text = "Diesen &Eintrag \r\nbearbeiten";
        Button1.UseVisualStyleBackColor = false;
        Button2.BackColor = Color.FromArgb(224, 224, 224);
        Button2.Font = new System.Drawing.Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button2.Location = new System.Drawing.Point(776, 29);
        Button2.Name = "btnRegisterSearch";
        Button2.Size = new System.Drawing.Size(86, 25);
        Button2.TabIndex = 2;
        Button2.Text = "&Schließen";
        Button2.UseVisualStyleBackColor = false;
        Button3.BackColor = Color.FromArgb(224, 224, 224);
        Button3.Enabled = false;
        Button3.Font = new System.Drawing.Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button3.Location = new System.Drawing.Point(722, 60);
        Button3.Name = "btnReenter";
        Button3.Size = new System.Drawing.Size(140, 23);
        Button3.TabIndex = 3;
        Button3.Text = "Quelle &bearbeiten";
        Button3.UseVisualStyleBackColor = false;
        Button4.BackColor = Color.FromArgb(224, 224, 224);
        Button4.Font = new System.Drawing.Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button4.Location = new System.Drawing.Point(665, 84);
        Button4.Name = "btnClose";
        Button4.Size = new System.Drawing.Size(197, 23);
        Button4.TabIndex = 4;
        Button4.Text = "Quellverbindung &hinzufügen";
        Button4.UseVisualStyleBackColor = false;
        Button5.BackColor = Color.FromArgb(224, 224, 224);
        Button5.Font = new System.Drawing.Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button5.Location = new System.Drawing.Point(665, 109);
        Button5.Name = "btnHometown";
        Button5.Size = new System.Drawing.Size(197, 23);
        Button5.TabIndex = 5;
        Button5.Text = "Quellverbindung löschen";
        Button5.UseVisualStyleBackColor = false;
        ComboBox1.FormattingEnabled = true;
        ComboBox1.Location = new System.Drawing.Point(131, 29);
        ComboBox1.Name = "ComboBox1";
        ComboBox1.Size = new System.Drawing.Size(639, 25);
        ComboBox1.TabIndex = 7;
        TextBox1.Location = new System.Drawing.Point(130, 134);
        TextBox1.Name = "edtPredicate";
        TextBox1.Size = new System.Drawing.Size(420, 25);
        TextBox1.TabIndex = 8;
        TextBox1.Visible = false;
        RTB.Font = new System.Drawing.Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        RTB.Location = new System.Drawing.Point(3, 204);
        RTB.Name = "RTB";
        RTB.Size = new System.Drawing.Size(859, 106);
        RTB.TabIndex = 10;
        RTB.Text = "";
        Option1.AutoSize = true;
        Option1.BackColor = Color.FromArgb(224, 224, 224);
        Option1.Font = new System.Drawing.Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Option1.Location = new System.Drawing.Point(570, 173);
        Option1.Name = "Option1";
        Option1.Size = new System.Drawing.Size(88, 21);
        Option1.TabIndex = 11;
        Option1.TabStop = true;
        Option1.Text = "nach Titel";
        Option1.UseVisualStyleBackColor = false;
        Option1.Visible = false;
        Option2.AutoSize = true;
        Option2.BackColor = Color.FromArgb(224, 224, 224);
        Option2.Font = new System.Drawing.Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Option2.Location = new System.Drawing.Point(570, 134);
        Option2.Name = "Option2";
        Option2.Size = new System.Drawing.Size(89, 21);
        Option2.TabIndex = 12;
        Option2.TabStop = true;
        Option2.Text = "nach Zitat";
        Option2.UseVisualStyleBackColor = false;
        Option2.Visible = false;
        ListBox1.Font = new System.Drawing.Font("Arial", 11f);
        ListBox1.FormattingEnabled = true;
        ListBox1.ItemHeight = 17;
        ListBox1.Location = new System.Drawing.Point(3, 204);
        ListBox1.Name = "ListBox1";
        ListBox1.Size = new System.Drawing.Size(859, 106);
        ListBox1.TabIndex = 13;
        ListBox1.Visible = false;
        Button7.BackColor = Color.FromArgb(224, 224, 224);
        Button7.Location = new System.Drawing.Point(3, 78);
        Button7.Name = "btnProperty";
        Button7.Size = new System.Drawing.Size(231, 23);
        Button7.TabIndex = 14;
        Button7.Text = "&Quelle wiederholen u. verlassen";
        Button7.UseVisualStyleBackColor = false;
        Label3.AutoEllipsis = true;
        Label3.BackColor = Color.Gainsboro;
        Label3.Location = new System.Drawing.Point(240, 78);
        Label3.Name = "lblDisplayHint";
        Label3.Size = new System.Drawing.Size(419, 50);
        Label3.TabIndex = 16;
        Label2.AutoSize = true;
        Label2.Location = new System.Drawing.Point(0, 138);
        Label2.Name = "lblState";
        Label2.Size = new System.Drawing.Size(129, 17);
        Label2.TabIndex = 17;
        Label2.Text = "Quelle beginnt mit:";
        Label2.Visible = false;
        Label4.AutoSize = true;
        Label4.Location = new System.Drawing.Point(28, 173);
        Label4.Name = "lblSearch";
        Label4.Size = new System.Drawing.Size(97, 17);
        Label4.TabIndex = 18;
        Label4.Text = "Quelle enthält";
        Label4.Visible = false;
        TextBox2.Location = new System.Drawing.Point(131, 170);
        TextBox2.Name = "edtSuburb";
        TextBox2.Size = new System.Drawing.Size(419, 25);
        TextBox2.TabIndex = 19;
        TextBox2.Visible = false;
        Button6.BackColor = Color.Lime;
        Button6.Location = new System.Drawing.Point(702, 167);
        Button6.Name = "btnDeleteQuiet";
        Button6.Size = new System.Drawing.Size(110, 23);
        Button6.TabIndex = 20;
        Button6.Text = "Suche Start";
        Button6.UseVisualStyleBackColor = false;
        Button6.Visible = false;
        Button8.BackColor = Color.FromArgb(224, 224, 224);
        Button8.Font = new System.Drawing.Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        Button8.Location = new System.Drawing.Point(665, 138);
        Button8.Name = "btnCancel";
        Button8.Size = new System.Drawing.Size(197, 23);
        Button8.TabIndex = 21;
        Button8.Text = "neue Quelle eintragen";
        Button8.UseVisualStyleBackColor = false;
        Button8.Visible = false;
        Button9.BackColor = Color.FromArgb(224, 224, 224);
        Button9.Location = new System.Drawing.Point(3, 105);
        Button9.Name = "btnCancel4";
        Button9.Size = new System.Drawing.Size(231, 23);
        Button9.TabIndex = 22;
        Button9.Text = "&Quelle wiederholen u. bearbeiten";
        Button9.UseVisualStyleBackColor = false;
        AutoScaleDimensions = new System.Drawing.SizeF(8f, 17f);
        AutoScaleMode = AutoScaleMode.Font;
        BackColor = Color.FromArgb(255, 224, 192);
        ClientSize = new System.Drawing.Size(874, 346);
        ControlBox = false;
        Button1.Click += new EventHandler(Button1_Click);
        Button2.Click += new EventHandler(Button2_Click);
        Button3.Click += new EventHandler(Button3_Click);
        Button4.Click += new EventHandler(Button4_Click);
        Button5.Click += new EventHandler(Button5_Click);
        ComboBox1.TextChanged += new EventHandler(ComboBox1_TextChanged);
        TextBox1.KeyDown += new KeyEventHandler(TextBox1_KeyDown);
        TextBox1.TextChanged += new EventHandler(TextBox1_TextChanged);
        Option2.CheckedChanged += new EventHandler(Option2_CheckedChanged);
        ListBox1.SelectedIndexChanged += new EventHandler(ListBox1_SelectedIndexChanged);
        ListBox1.DoubleClick += new EventHandler(ListBox1_DoubleClick);
        RTB.KeyDown += new KeyEventHandler(RTB_KeyDown);
        Button7.Click += new EventHandler(Button7_Click);
        TextBox2.TextChanged += new EventHandler(TextBox2_TextChanged);
        Button6.Click += new EventHandler(Button6_Click);
        Button8.Click += new EventHandler(Button8_Click);
        Button9.Click += new EventHandler(Button9_Click);
        Controls.Add(Button9);
        Controls.Add(Button8);
        Controls.Add(Button6);
        Controls.Add(TextBox2);
        Controls.Add(Label4);
        Controls.Add(Label2);
        Controls.Add(Label3);
        Controls.Add(Button7);
        Controls.Add(ListBox1);
        Controls.Add(Option2);
        Controls.Add(Option1);
        Controls.Add(RTB);
        Controls.Add(TextBox1);
        Controls.Add(ComboBox1);
        Controls.Add(Button5);
        Controls.Add(Button4);
        Controls.Add(Button3);
        Controls.Add(Button2);
        Controls.Add(Button1);
        Controls.Add(Label1);
        Font = new System.Drawing.Font("Arial", 8.5f, FontStyle.Regular, GraphicsUnit.Point, 0);
        FormBorderStyle = FormBorderStyle.FixedSingle;
        Margin = new System.Windows.Forms.Padding(4);
        Name = "Quellen";
        SizeGripStyle = SizeGripStyle.Hide;
        StartPosition = FormStartPosition.CenterScreen;
        Text = " ";
        ResumeLayout(false);
        PerformLayout();
    }


}
