using CustomerRepository.Model;
using CustomerRepository.Model.Factory;

namespace CustomerRepositoryTests.Model
{
    /// <summary>Class CusomerRepository3.
    /// Implements the <see cref="ICustomerRepository" /></summary>
    /// <remarks>This repository uses a <b>abtract Factory</b></remarks>
    /// <autogeneratedoc />
    public class CustomerRepository3 : ICustomerRepository2
    {
        #region Properties
        #region private properties
        private Dictionary<Guid,CCustomer> _customers=new Dictionary<Guid, CCustomer>();
        #endregion
        public IClock Clock { get; }
        public ILog Log { get; }
        public long Count => throw new NotImplementedException();
        #endregion

        public CustomerRepository3(IClockFactory clockFactory,ILogFactory logFactory)
        {
            Clock = clockFactory.Get();
            Log = logFactory.Get();
        }

        public CCustomer Get(Guid id)
        {
            CCustomer result;
            if(!_customers.TryGetValue(id, out result))
            {
                Log.Error(Clock.Now, "no such customer");
                throw new ArgumentException("no such customer");
            }
            return result;
        }

        public Guid Put(CCustomer customer)
        {
            throw new NotImplementedException();
        }


    }
}