//------------------------------------------------------------------------------
// <auto-generated>
//  This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Avln_CustomAnimation.Properties {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
      
      private static global::System.Resources.ResourceManager? resourceMan;
        
        private static global::System.Globalization.CultureInfo? resourceCulture;
        
  [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
  
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
   public static global::System.Resources.ResourceManager ResourceManager {
            get {
        if (object.ReferenceEquals(resourceMan, null)) {
               global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avln_CustomAnimation.Properties.Resources", typeof(Resources).Assembly);
     resourceMan = temp;
       }
     return resourceMan;
    }
        }
        
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo? Culture {
    get {
          return resourceCulture;
            }
        set {
                resourceCulture = value;
    }
   }
      
        public static string Description {
         get {
       return ResourceManager.GetString("Description", resourceCulture) ?? "";
            }
        }
        
      public static string Title {
    get {
 return ResourceManager.GetString("Title", resourceCulture) ?? "";
      }
        }
    }
}
