<Project>
  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <EnableMSTestRunner Condition="'$(EnableMSTestRunner)' == ''">true</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport Condition="'$(TestingPlatformDotnetTestSupport)' == ''">true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestProject)' == 'true'">
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" PrivateAssets="all" />
  </ItemGroup>
</Project>
