// ***********************************************************************
// Assembly         : MVVM_41_Sudoku
// Author           : Mir
// Created          : 05-19-2023
//
// Last Modified By : Mir
// Last Modified On : 05-19-2023
// ***********************************************************************
// <copyright file="ISudokuModel.cs" company="JC-Soft">
//     Copyright © JC-Soft 2023
// </copyright>
// <summary></summary>
// ***********************************************************************
using CommunityToolkit.Mvvm.Input;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;

/// <summary>
/// The Models namespace.
/// </summary>
/// <autogeneratedoc />
namespace Sudoku_Base.Models.Interfaces
{
    /// <summary>
    /// Interface ISudokuModel
    /// </summary>
    /// <autogeneratedoc />
    public interface ISudokuModel : INotifyPropertyChanged
    {
        IReadOnlyList<ISudokuField> Fields { get; }

        void Clear();

        IRelayCommand UndoCommand { get; }
        IRelayCommand RedoCommand { get; }

        bool WriteToStream(Stream stream,bool xInclState);

        bool ReadFromStream(Stream stream);
    }
}
