// <auto-generated>
// This file contains unit tests for the DbSelectStatement constructor in Db.Core.Abstractions.Sql.
// Coverage focus: All constructor logic and property assignments, including null/empty/whitespace table, fields, filters, and limit edge cases.
// Framework: MSTest v4.2.2, Mocks: NSubstitute v5.3.0
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using Db.Core.Abstractions.Sql;
using Db.Core.Abstractions.Sql.Interfaaces;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using NSubstitute;

namespace DbCoreAbstractions.UnitTests.Sql
{
    /// <summary>
    /// Unit tests for <see cref="DbSelectStatement"/> constructor.
    /// </summary>
    [TestClass]
    public class DbSelectStatementTests
    {
        [TestMethod]
        public void Ctor_ValidArguments_PropertiesSetCorrectly()
        {
            // Arrange
            var table = "MyTable";
            var fields = new[] { "Id", "Name" };
            var filter1 = Substitute.For<IDbFilterClause>();
            var filter2 = Substitute.For<IDbFilterClause>();
            var filters = new[] { filter1, filter2 };
            int? limit = 10;

            // Act
            var stmt = new DbSelectStatement(table, fields, filters, limit);

            // Assert
            Assert.AreEqual(table, stmt.Table);
            CollectionAssert.AreEqual(fields, stmt.Fields.ToArray());
            CollectionAssert.AreEqual(filters, stmt.Filters.ToArray());
            Assert.AreEqual(limit, stmt.Limit);
        }

        [TestMethod]
        [DataRow(null)]
        [DataRow("")]
        [DataRow("   ")]
        public void Ctor_TableNullOrWhiteSpace_ThrowsArgumentException(string? table)
        {
            // Arrange
            IEnumerable<string>? fields = null;
            IEnumerable<IDbFilterClause>? filters = null;
            int? limit = null;

            // Act & Assert
            try
            {
                _ = new DbSelectStatement(table!, fields, filters, limit);
                Assert.Fail("Expected ArgumentException was not thrown.");
            }
            catch (ArgumentException ex)
            {
                StringAssert.Contains(ex.Message, "table");
                Assert.AreEqual("table", ex.ParamName);
            }
        }

        [TestMethod]
        public void Ctor_FieldsNull_FieldsIsEmpty()
        {
            // Arrange
            var table = "T";
            IEnumerable<string>? fields = null;
            var filter = Substitute.For<IDbFilterClause>();
            var filters = new[] { filter };
            int? limit = null;

            // Act
            var stmt = new DbSelectStatement(table, fields, filters, limit);

            // Assert
            Assert.AreEqual(0, stmt.Fields.Count);
        }

        [TestMethod]
        public void Ctor_FiltersNull_FiltersIsEmpty()
        {
            // Arrange
            var table = "T";
            var fields = new[] { "A" };
            IEnumerable<IDbFilterClause>? filters = null;
            int? limit = null;

            // Act
            var stmt = new DbSelectStatement(table, fields, filters, limit);

            // Assert
            Assert.AreEqual(0, stmt.Filters.Count);
        }

        [TestMethod]
        public void Ctor_LimitNull_LimitIsNull()
        {
            // Arrange
            var table = "T";
            var fields = new[] { "A" };
            var filter = Substitute.For<IDbFilterClause>();
            var filters = new[] { filter };
            int? limit = null;

            // Act
            var stmt = new DbSelectStatement(table, fields, filters, limit);

            // Assert
            Assert.IsNull(stmt.Limit);
        }

    }
}
