<Project>
    <PropertyGroup>
        <TargetFrameworks>net8.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <EnableMSTestRunner>true</EnableMSTestRunner>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>
    <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.props" />
    <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.targets" />
    <ItemGroup>
        <PackageReference Include="MSTest" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="coverlet.collector" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Ollama.CodingAgent\Ollama.CodingAgent.csproj" />
        <ProjectReference Include="..\OpenAI.CodingAgent\OpenAI.CodingAgent.csproj" />
        <ProjectReference Include="..\..\Data\CommandlineHelper\CommandlineHelper.csproj" />
    </ItemGroup>
</Project>
