//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde manuell erstellt, um stark typisierte Ressourcen in Abwesenheit des
//     Standard-Generators bereitzustellen.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace TileSetAnimator.Properties;

using System;
using System.Globalization;
using System.Resources;

/// <summary>
/// Provides strongly typed accessors for localized resources.
/// </summary>
public class Resources
{
    private static ResourceManager? resourceMan;

    private static CultureInfo? resourceCulture;

    internal Resources()
    {
    }

    /// <summary>
    /// Gets the cached ResourceManager instance used by this class.
    /// </summary>
    public static ResourceManager ResourceManager
        => resourceMan ??= new ResourceManager("TileSetAnimator.Properties.Resources", typeof(Resources).Assembly);

    /// <summary>
    /// Overrides the current thread's CurrentUICulture property for all resource lookups.
    /// </summary>
    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string AddFrameButtonText => ResourceManager.GetString("AddFrameButtonText", resourceCulture) ?? string.Empty;

    public static string AnimationCountFormat => ResourceManager.GetString("AnimationCountFormat", resourceCulture) ?? string.Empty;

    public static string AnimationListTitle => ResourceManager.GetString("AnimationListTitle", resourceCulture) ?? string.Empty;

    public static string AnimationSettingsGroupTitle => ResourceManager.GetString("AnimationSettingsGroupTitle", resourceCulture) ?? string.Empty;

    public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture) ?? string.Empty;

    public static string ClearFramesButtonText => ResourceManager.GetString("ClearFramesButtonText", resourceCulture) ?? string.Empty;

    public static string CommitAnimationButtonText => ResourceManager.GetString("CommitAnimationButtonText", resourceCulture) ?? string.Empty;

    public static string DetectAnimationsButtonText => ResourceManager.GetString("DetectAnimationsButtonText", resourceCulture) ?? string.Empty;

    public static string FileGroupTitle => ResourceManager.GetString("FileGroupTitle", resourceCulture) ?? string.Empty;

    public static string FrameDurationLabel => ResourceManager.GetString("FrameDurationLabel", resourceCulture) ?? string.Empty;

    public static string LoadSheetButtonText => ResourceManager.GetString("LoadSheetButtonText", resourceCulture) ?? string.Empty;

    public static string MarginLabel => ResourceManager.GetString("MarginLabel", resourceCulture) ?? string.Empty;

    public static string MiniMapApplySuggestionButtonText => ResourceManager.GetString("MiniMapApplySuggestionButtonText", resourceCulture) ?? string.Empty;

    public static string MiniMapClearButtonText => ResourceManager.GetString("MiniMapClearButtonText", resourceCulture) ?? string.Empty;

    public static string MiniMapClearSlotButtonText => ResourceManager.GetString("MiniMapClearSlotButtonText", resourceCulture) ?? string.Empty;

    public static string MiniMapGroupTitle => ResourceManager.GetString("MiniMapGroupTitle", resourceCulture) ?? string.Empty;

    public static string MiniMapSuggestedSlotLabel => ResourceManager.GetString("MiniMapSuggestedSlotLabel", resourceCulture) ?? string.Empty;

    public static string MiniMapPlaceTileButtonText => ResourceManager.GetString("MiniMapPlaceTileButtonText", resourceCulture) ?? string.Empty;

    public static string MinimumAnimationLengthLabel => ResourceManager.GetString("MinimumAnimationLengthLabel", resourceCulture) ?? string.Empty;

    public static string NewAnimationButtonText => ResourceManager.GetString("NewAnimationButtonText", resourceCulture) ?? string.Empty;

    public static string NoSheetLoadedMessage => ResourceManager.GetString("NoSheetLoadedMessage", resourceCulture) ?? string.Empty;

    public static string PendingAnimationGroupTitle => ResourceManager.GetString("PendingAnimationGroupTitle", resourceCulture) ?? string.Empty;

    public static string PendingAnimationHint => ResourceManager.GetString("PendingAnimationHint", resourceCulture) ?? string.Empty;

    public static string PreviewGroupTitle => ResourceManager.GetString("PreviewGroupTitle", resourceCulture) ?? string.Empty;

    public static string SaveTileButtonText => ResourceManager.GetString("SaveTileButtonText", resourceCulture) ?? string.Empty;

    public static string SaveTileDialogTitle => ResourceManager.GetString("SaveTileDialogTitle", resourceCulture) ?? string.Empty;

    public static string SelectedTileHeader => ResourceManager.GetString("SelectedTileHeader", resourceCulture) ?? string.Empty;

    public static string SelectTileFirstMessage => ResourceManager.GetString("SelectTileFirstMessage", resourceCulture) ?? string.Empty;

    public static string SpacingLabel => ResourceManager.GetString("SpacingLabel", resourceCulture) ?? string.Empty;

    public static string StartPreviewButtonText => ResourceManager.GetString("StartPreviewButtonText", resourceCulture) ?? string.Empty;

    public static string StopPreviewButtonText => ResourceManager.GetString("StopPreviewButtonText", resourceCulture) ?? string.Empty;

    public static string TileCatalogHeader => ResourceManager.GetString("TileCatalogHeader", resourceCulture) ?? string.Empty;

    public static string TileCountFormat => ResourceManager.GetString("TileCountFormat", resourceCulture) ?? string.Empty;

    public static string TileHeightLabel => ResourceManager.GetString("TileHeightLabel", resourceCulture) ?? string.Empty;

    public static string TileNameLabel => ResourceManager.GetString("TileNameLabel", resourceCulture) ?? string.Empty;

    public static string TileNotesLabel => ResourceManager.GetString("TileNotesLabel", resourceCulture) ?? string.Empty;

    public static string TileSettingsGroupTitle => ResourceManager.GetString("TileSettingsGroupTitle", resourceCulture) ?? string.Empty;

    public static string TileSheetExpanderTitle => ResourceManager.GetString("TileSheetExpanderTitle", resourceCulture) ?? string.Empty;

    public static string TileMetadataExpanderTitle => ResourceManager.GetString("TileMetadataExpanderTitle", resourceCulture) ?? string.Empty;

    public static string AnimationToolsExpanderTitle => ResourceManager.GetString("AnimationToolsExpanderTitle", resourceCulture) ?? string.Empty;

    public static string TileClassKeyLabel => ResourceManager.GetString("TileClassKeyLabel", resourceCulture) ?? string.Empty;

    public static string MiniMapSelectionLabel => ResourceManager.GetString("MiniMapSelectionLabel", resourceCulture) ?? string.Empty;

    public static string MiniMapNameLabel => ResourceManager.GetString("MiniMapNameLabel", resourceCulture) ?? string.Empty;

    public static string MiniMapAddButtonText => ResourceManager.GetString("MiniMapAddButtonText", resourceCulture) ?? string.Empty;

    public static string MiniMapRemoveButtonText => ResourceManager.GetString("MiniMapRemoveButtonText", resourceCulture) ?? string.Empty;

    public static string MiniMapPreviewHeader => ResourceManager.GetString("MiniMapPreviewHeader", resourceCulture) ?? string.Empty;

    public static string TileWidthLabel => ResourceManager.GetString("TileWidthLabel", resourceCulture) ?? string.Empty;

    public static string ZoomLabel => ResourceManager.GetString("ZoomLabel", resourceCulture) ?? string.Empty;

    public static string TileCategoryLabel => ResourceManager.GetString("TileCategoryLabel", resourceCulture) ?? string.Empty;

    public static string TileSubCategoryLabel => ResourceManager.GetString("TileSubCategoryLabel", resourceCulture) ?? string.Empty;

    public static string ExportTileEnumButtonText => ResourceManager.GetString("ExportTileEnumButtonText", resourceCulture) ?? string.Empty;

    public static string ImportTileEnumButtonText => ResourceManager.GetString("ImportTileEnumButtonText", resourceCulture) ?? string.Empty;

    public static string ExportTileEnumDialogTitle => ResourceManager.GetString("ExportTileEnumDialogTitle", resourceCulture) ?? string.Empty;

    public static string ImportTileEnumDialogTitle => ResourceManager.GetString("ImportTileEnumDialogTitle", resourceCulture) ?? string.Empty;
}
