// ***********************************************************************
// Assembly         : Snake_BaseTests
// Author           : Mir
// Created          : 08-24-2022
//
// Last Modified By : Mir
// Last Modified On : 09-09-2022
// ***********************************************************************
// <copyright file="TestItem.cs" company="JC-Soft">
//     Copyright (c) HP JC-Soft. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Drawing;

/// <summary>
/// The Tests namespace.
/// </summary>
/// <autogeneratedoc />
namespace Game.Model.Tests;

/// <summary>
/// Class TestItem.
/// Inherits the shared placed-item test behavior from <see cref="TestPlacedItemBase{TSelf}" />.
/// </summary>
public class TestItem : TestPlacedItemBase<TestItem>
{
  
    /// <summary>
    /// Returns a <see cref="System.String" /> that represents this instance.
    /// </summary>
    /// <returns>A <see cref="System.String" /> that represents this instance.</returns>
    public override string ToString() => $"TestItem({Name},{GetPlace()})";

}
