// ***********************************************************************
// Assembly         : Snake_BaseTests
// Author           : Mir
// Created          : 08-24-2022
//
// Last Modified By : Mir
// Last Modified On : 09-09-2022
// ***********************************************************************
// <copyright file="TestParent.cs" company="JC-Soft">
//     Copyright (c) HP JC-Soft. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using BaseLib.Helper;
using BaseLib.Interfaces;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Runtime.CompilerServices;
using Game.Model.Interfaces;

/// <summary>
/// The Tests namespace.
/// </summary>
/// <autogeneratedoc />
namespace Game.Model.Tests;

/// <summary>
/// Class TestParent.
/// Implements the <see cref="BaseLib.Interfaces.IHasChildren{Snake_Base.Model.Field{Snake_Base.Model.Tests.TestItem}}" />
/// Implements the <see cref="IPlacedObject" />
/// </summary>
/// <seealso cref="BaseLib.Interfaces.IHasChildren{Snake_Base.Model.Field{Snake_Base.Model.Tests.TestItem}}" />
/// <seealso cref="IPlacedObject" />
internal class TestParent : IHasChildren<Field<TestItem>>, IPlacedObject
{
    /// <summary>
    /// The place
    /// </summary>
    internal Point _place;
    /// <summary>
    /// The oldplace
    /// </summary>
    /// <autogeneratedoc />
    private Point _oldplace;
    /// <summary>
    /// The items
    /// </summary>
    public List<Field<TestItem>> _items = [];

    /// <summary>
    /// The log operation
    /// </summary>
    internal static Action<string, TestParent, object?, object?, string>? logOperation;
    /// <summary>
    /// The name
    /// </summary>
    public string Name="";

    /// <summary>
    /// Occurs when [on place change].
    /// </summary>
    public event EventHandler<(Point oP, Point nP)> OnPlaceChange;

    /// <summary>
    /// Initializes a new instance of the <see cref="TestParent" /> class.
    /// </summary>
    public TestParent() : this("", Point.Empty) { }
    /// <summary>
    /// Initializes a new instance of the <see cref="TestParent" /> class.
    /// </summary>
    /// <param name="name">The name.</param>
    /// <param name="place">The place.</param>
    public TestParent(string name,Point place)
    {
        _oldplace = 
        _place = place;
        Name = name;
    }

    /// <summary>
    /// Adds the item.
    /// </summary>
    /// <param name="value">The value.</param>
    /// <returns><c>true</c> if XXXX, <c>false</c> otherwise.</returns>
    public bool AddItem(Field<TestItem> value)
    {
        _items.Add(value);
        LogOperation("Items.Add", null, value);
        return true;
    }

    /// <summary>
    /// Gets the items.
    /// </summary>
    /// <returns>IEnumerable&lt;Field&lt;TestItem&gt;&gt;.</returns>
    public IEnumerable<Field<TestItem>> GetItems() => _items;
    /// <summary>
    /// Removes the item.
    /// </summary>
    /// <param name="value">The value.</param>
    /// <returns><c>true</c> if XXXX, <c>false</c> otherwise.</returns>
    public bool RemoveItem(Field<TestItem> value)
    {
        _items.Remove(value);
        LogOperation("Items.Remove", value, null);
        return true;
    }

    /// <summary>
    /// Gets the old place.
    /// </summary>
    /// <returns>Point.</returns>
    public Point GetOldPlace() => _oldplace;
    /// <summary>
    /// Gets the place.
    /// </summary>
    /// <returns>Point.</returns>
    public Point GetPlace() => _place;
    /// <summary>
    /// Sets the place.
    /// </summary>
    /// <param name="value">The value.</param>
    /// <param name="Name">The name.</param>
    public void SetPlace(Point value, [CallerMemberName] string Name = "") => value.SetProperty(ref _place, 
        (s, o, n) => { _oldplace = o; OnPlaceChange?.Invoke(this, ((Point)n, (Point)o)); logOperation?.Invoke("Place changed", this, o, n, s); }, Name);

    /// <summary>
    /// Returns a <see cref="System.String" /> that represents this instance.
    /// </summary>
    /// <returns>A <see cref="System.String" /> that represents this instance.</returns>
    public override string ToString()
    {
        return $"TestParent({Name},{GetPlace()})";
    }

    /// <summary>
    /// Logs the operation.
    /// </summary>
    /// <param name="v">The v.</param>
    /// <param name="old">The old.</param>
    /// <param name="parent">The parent.</param>
    /// <param name="callerMember">The caller member.</param>
    /// <autogeneratedoc />
    private void LogOperation(string v, object? old, object? parent,[CallerMemberName] string callerMember="") => logOperation?.Invoke(v, this, old, parent, callerMember);

    /// <summary>
    /// Notifies the child change.
    /// </summary>
    /// <param name="childObject">The child object.</param>
    /// <param name="oldVal">The old value.</param>
    /// <param name="newVal">The new value.</param>
    /// <param name="prop">The property.</param>
    public void NotifyChildChange(Field<TestItem> childObject, object oldVal, object newVal, [CallerMemberName] string prop = "")
    {
        
    }

    public override bool Equals(object? obj)
    {
        return obj is TestParent parent &&
               EqualityComparer<Point>.Default.Equals(_place, parent._place) &&
               EqualityComparer<List<Field<TestItem>>>.Default.Equals(_items, parent._items) &&
               Name == parent.Name;
    }

    public override int GetHashCode()
    {
        var hashCode = 1687199569;
        hashCode = hashCode * -1521134295 + _place.GetHashCode();
        hashCode = hashCode * -1521134295 + EqualityComparer<List<Field<TestItem>>>.Default.GetHashCode(_items);
        hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Name);
        return hashCode;
    }
}
