using BaseLib.Helper;
using BaseLib.Interfaces;
using Game.Model.Interfaces;
using System;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace Game.Model.Tests;

/// <summary>
/// Provides the shared test implementation for placed and parented test items.
/// </summary>
/// <typeparam name="TSelf">The concrete item type.</typeparam>
public abstract class TestPlacedItemBase<TSelf> : IPlacedObject, IParentedObject, IEquatable<TSelf>
    where TSelf : TestPlacedItemBase<TSelf>
{
    public static event Action<string, object, object?, object?, string>? logOperation;

    /// <summary>
    /// Stores the current parent reference.
    /// </summary>
    internal object? _parent;

    /// <summary>
    /// Stores the current place.
    /// </summary>
    public Point _place;

    /// <summary>
    /// Stores the previous place.
    /// </summary>
    protected Point _oldPlace;

    /// <summary>
    /// Gets or sets the public test name.
    /// </summary>
    public string Name = "";

    /// <summary>
    /// Occurs when the place changes.
    /// </summary>
    public event EventHandler<(Point oP, Point nP)>? OnPlaceChange;

#if NET6_0_OR_GREATER
    /// <summary>
    /// Gets or sets the parent through the interface pattern.
    /// </summary>
    public object? Parent
    {
        get => _parent;
        set => SetParent(value);
    }

    /// <summary>
    /// Gets or sets the place through the interface pattern.
    /// </summary>
    public Point Place
    {
        get => _place;
        set => SetPlace(value);
    }
#endif

    /// <summary>
    /// Determines whether the current instance is equal to another instance of the same type.
    /// </summary>
    /// <param name="other">The instance to compare.</param>
    /// <returns><see langword="true"/> when both instances use the same name; otherwise <see langword="false"/>.</returns>
    public bool Equals(TSelf? other) => other != null && other.Name == Name;

    /// <summary>
    /// Gets the current parent.
    /// </summary>
    /// <returns>The current parent reference.</returns>
    public object? GetParent() => _parent;

    /// <summary>
    /// Sets the current parent.
    /// </summary>
    /// <param name="value">The new parent value.</param>
    /// <param name="callerMember">The calling member name.</param>
    public void SetParent(object? value, [CallerMemberName] string callerMember = "")
    {
        if (_parent == value)
        {
            return;
        }

        var old = _parent;
        _parent = value;
        LogOperation("New Parent", old, value, callerMember);
    }

    /// <summary>
    /// Gets the current place.
    /// </summary>
    /// <returns>The current place.</returns>
    public Point GetPlace() => _place;

    /// <summary>
    /// Sets the current place.
    /// </summary>
    /// <param name="value">The new place.</param>
    /// <param name="name">The calling member name.</param>
    public void SetPlace(Point value, [CallerMemberName] string name = "")
        => value.SetProperty(
            ref _place,
            (s, o, n) =>
            {
                _oldPlace = (Point)o;
                OnPlaceChange?.Invoke(this, ((Point)o, (Point)n));
                LogOperation("Place changed", o, n, s);
            },
            name);

    /// <summary>
    /// Gets the previous place.
    /// </summary>
    /// <returns>The previous place.</returns>
    public Point GetOldPlace() => _oldPlace;

    /// <summary>
    /// Raises the type-specific logging event.
    /// </summary>
    /// <param name="operation">The operation name.</param>
    /// <param name="oldValue">The previous value.</param>
    /// <param name="newValue">The new value.</param>
    /// <param name="callerMember">The caller member.</param>
    /// <autogeneratedoc />
    private void LogOperation(string operation, object? oldValue, object? newValue, string callerMember)
        => logOperation?.Invoke(operation, this, oldValue, newValue, callerMember);
}
