<Project>
  <Import Project="..\ConsoleApps.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>false</UseWindowsForms>
    <Configurations>Debug;Release;DesktopOnly</Configurations>
  </PropertyGroup>
  <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.props" />
  <Import Sdk="Microsoft.NET.Sdk" Project="Sdk.targets" />
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\BaseLib\BaseLib.csproj" />
    <ProjectReference Include="..\..\Libraries\ConsoleLib\ConsoleLib.csproj" />
    <ProjectReference Include="..\..\Libraries\ConsoleLib.ExtCon\ConsoleLib.ExtCon.csproj" />
    <ProjectReference Include="..\..\Libraries\Terminal.Core\Terminal.Core.csproj" />
    <ProjectReference Include="..\ConsoleLib.Showcase.Terminal.Core\ConsoleLib.Showcase.Terminal.Core.csproj" />
  </ItemGroup>
</Project>
