//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVM_42_3DView.Properties;
using System;


/// <summary>
///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
/// </summary>
// Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
// -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
// Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
// mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class Resources {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }
    
    /// <summary>
    ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVVM_42_3DView.Properties.Resources", typeof(Resources).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die 3D-View with MVVM, DI, CommunityToolkit and Behaviors ähnelt.
    /// </summary>
    public static string Description {
        get {
            return ResourceManager.GetString("Description", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Page
    ///       xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    ///       xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    ///       xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
    ///       xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
    ///       xmlns:local="clr-namespace:MVVM_42_3DView.Views"
    ///       xmlns:p="clr-namespace:MVVM_42_3DView.Properties"
    ///       xmlns:mvvm="clr-namespace:MVVM_42_3DView.ViewModels"
    ///       xmlns:i="http://schemas.microsoft.com/xaml/behaviors"
    ///       x:Class="MVVM_42_3DView.Views.ThreeDView"
    ///       mc:Ignorable="d" 
    ///       d:DesignHeight="450" d:DesignWidth="800"
    ///       Title="{x:Static p:Resources.Title}">
    ///     &lt;Page.DataContext&gt;
    ///         &lt;mvvm:ThreeDViewModel /&gt;
    ///     &lt;/Page.DataContext&gt;
    ///     &lt;Grid Background="#FF1E1E1E"&gt;
    ///         &lt;Viewport3D ClipToBounds="True"&gt;
    ///             &lt;Viewport3D.Camera&gt;
    ///                 &lt;PerspectiveCamera Position="{Binding CameraPosition}"
    ///                                    LookDirection="{Binding CameraLookDirection}"
    ///                                    UpDirection="{Binding CameraUpDirection}"
    ///                                    FieldOfView="60" /&gt;
    ///             &lt;/Viewport3D.Camera&gt;
    ///             &lt;ModelVisual3D&gt;
    ///                 &lt;ModelVisual3D.Content&gt;
    ///                     &lt;DirectionalLight Color="White" Direction="{Binding LightDirection}" /&gt;
    ///                 &lt;/ModelVisual3D.Content&gt;
    ///             &lt;/ModelVisual3D&gt;
    ///             &lt;ModelVisual3D&gt;
    ///                 &lt;ModelVisual3D.Content&gt;
    ///                     &lt;GeometryModel3D Geometry="{Binding Geometry}"&gt;
    ///                         &lt;GeometryModel3D.Material&gt;
    ///                             &lt;DiffuseMaterial Brush="{Binding ModelBrush}" /&gt;
    ///                         &lt;/GeometryModel3D.Material&gt;
    ///                         &lt;GeometryModel3D.Transform&gt;
    ///                             &lt;RotateTransform3D&gt;
    ///                                 &lt;RotateTransform3D.Rotation&gt;
    ///                                     &lt;AxisAngleRotation3D Axis="{Binding RotationAxis}" Angle="{Binding RotationAngle}" /&gt;
    ///                                 &lt;/RotateTransform3D.Rotation&gt;
    ///                             &lt;/RotateTransform3D&gt;
    ///                         &lt;/GeometryModel3D.Transform&gt;
    ///                     &lt;/GeometryModel3D&gt;
    ///                 &lt;/ModelVisual3D.Content&gt;
    ///             &lt;/ModelVisual3D&gt;
    ///         &lt;/Viewport3D&gt;
    ///         &lt;i:Interaction.Triggers&gt;
    ///             &lt;i:EventTrigger EventName="Loaded"&gt;
    ///                 &lt;i:InvokeCommandAction Command="{Binding ResetCameraCommand}" /&gt;
    ///             &lt;/i:EventTrigger&gt;
    ///         &lt;/i:Interaction.Triggers&gt;
    ///     &lt;/Grid&gt;
    /// &lt;/Page&gt; ähnelt.
    /// </summary>
    public static string ThreeDView {
        get {
            return ResourceManager.GetString("ThreeDView", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die // ***********************************************************************
    /// // Assembly         : MVVM_42_3DView
    /// // Author           : Mir
    /// // Created          : 03-09-2025
    /// //
    /// // Last Modified By : Mir
    /// // Last Modified On : 03-09-2025
    /// // ***********************************************************************
    /// // &lt;copyright file="ThreeDViewModel.cs" company="JC-Soft"&gt;
    /// //     Copyright © JC-Soft 2025
    /// // &lt;/copyright&gt;
    /// // &lt;summary&gt;&lt;/summary&gt;
    /// // ***********************************************************************
    /// using BaseLib.Helper;
    /// using CommunityToolkit.Mvvm.Input;
    /// using MVVM.ViewModel;
    /// using MVVM_42_3DView.Models;
    /// using System.ComponentModel;
    /// using System.Windows.Media;
    /// using System.Windows.Media.Media3D;
    ///
    /// namespace MVVM_42_3DView.ViewModels;
    ///
    /// /// &lt;summary&gt;
    /// /// Class ThreeDViewModel.
    /// /// Implements the &lt;see cref="BaseViewModelCT" /&gt;
    /// /// &lt;/summary&gt;
    /// /// &lt;seealso cref="BaseViewModelCT" /&gt;
    /// public partial class ThreeDViewModel : BaseViewModelCT
    /// {
    ///     #region Properties
    ///     private readonly ISceneModel _model;
    ///
    ///     public MeshGeometry3D Geometry =&gt; _model.Geometry;
    ///     public Brush ModelBrush =&gt; _model.ModelBrush;
    ///     public Vector3D LightDirection =&gt; _model.LightDirection;
    ///     public Vector3D RotationAxis =&gt; _model.RotationAxis;
    ///     public double RotationAngle =&gt; _model.RotationAngle;
    ///     public Point3D CameraPosition =&gt; _model.CameraPosition;
    ///     public Vector3D CameraLookDirection =&gt; _model.CameraLookDirection;
    ///     public Vector3D CameraUpDirection =&gt; _model.CameraUpDirection;
    ///     #endregion
    ///
    ///     #region Methods
    ///     /// &lt;summary&gt;
    ///     /// Initializes a new instance of the &lt;see cref="ThreeDViewModel"/&gt; class.
    ///     /// &lt;/summary&gt;
    ///     public ThreeDViewModel() : this(IoC.GetRequiredService&lt;ISceneModel&gt;())
    ///     {
    ///     }
    ///
    ///     public ThreeDViewModel(ISceneModel model)
    ///     {
    ///         _model = model;
    ///         _model.PropertyChanged += OnModelPropertyChanged;
    ///     }
    ///
    ///     private void OnModelPropertyChanged(object? sender, PropertyChangedEventArgs e)
    ///     {
    ///         OnPropertyChanged(e.PropertyName);
    ///     }
    ///
    ///     [RelayCommand]
    ///     private void ResetCamera()
    ///     {
    ///         _model.ResetCamera();
    ///     }
    ///
    ///     #endregion
    /// } ähnelt.
    /// </summary>
    public static string ThreeDViewModel {
        get {
            return ResourceManager.GetString("ThreeDViewModel", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Sucht eine lokalisierte Zeichenfolge, die 3D-View ähnelt.
    /// </summary>
    public static string Title {
        get {
            return ResourceManager.GetString("Title", resourceCulture);
        }
    }
}
