<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Application.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RnzTrauer.Persistence.MySql\RnzTrauer.Persistence.MySql.csproj" />
  </ItemGroup>
</Project>
