namespace WinAhnenCls.Model.GenBase
{
    public enum EEventType
    {
        evt_ID = 0,
        evt_Birth = 1,
        evt_Baptism = 2,
        evt_Marriage = 3,
        evt_Death = 4,
        evt_Burial = 5,
        evt_Sex = 6,
        evt_Occupation = 7,
        evt_Religion = 8,
        evt_Residence = 9,
        evt_GivenName = 10,
        evt_AKA = 11,
        evt_AddOccupation = 12,
        evt_AddResidence = 13,
        evt_AddEmigration = 14,
        evt_Confirmation = 15,
        evt_Military = 16,
        evt_Divorce = 17,
        evt_Education = 18,
        evt_Degree = 19,
        evt_Anull = 20,
        evt_BarMitzwah = 21,
        evt_BasMitzwah = 22,
        evt_Blessing = 23,
        evt_Cast = 24,
        evt_Cencus = 25,
        evt_Member = 26,
        evt_Ordination,
        evt_Graduation,
        evt_FreeEvent,
        evt_Adoption,
        evt_Cremation,
        evt_Immigration,
        evt_Naturalization,
        evt_Probation,
        evt_Retirement,
        evt_LastWill,
        evt_FreeFact,
        evt_Description,
        evt_Uid,
        evt_FamilySearchID,
        evt_Property,
        evt_Assosiation,
        evt_Stillborn,
        evt_Partner,
        evt_fallen,
        evt_missing,
        evt_Age,
        evt_Info,

        evt_LastChange,
        evt_Last
    }
}
