// ***********************************************************************
// Assembly         : MVVM_00a_CTTemplate_netTests
// Author           : Mir
// Created          : 05-14-2023
//
// Last Modified By : Mir
// Last Modified On : 05-14-2023
// ***********************************************************************
// <copyright file="MainWindowTests.cs" company="JC-Soft">
//     Copyright © JC-Soft 2023
// </copyright>
// <summary></summary>
// ***********************************************************************
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Avalonia.ViewModels;
using AA09_DialogBoxes.ViewModels;
using AA09_DialogBoxes.Messages;
using NSubstitute;
using CommunityToolkit.Mvvm.Messaging;
using System;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// The Tests namespace.
/// </summary>
/// <autogeneratedoc />
namespace AA09_DialogBoxes.Views.Tests;

/// <summary>
/// Defines test class MainWindowTests.
/// </summary>
/// <autogeneratedoc />
[TestClass()]
public class MainWindowTests : BaseTestViewModel
{
#pragma warning disable CS8618 // Ein Non-Nullable-Feld muss beim Beenden des Konstruktors einen Wert ungleich NULL enthalten. Erwägen Sie die Deklaration als Nullable.
    /// <summary>
    /// The test view
    /// </summary>
    /// <autogeneratedoc />
    MainWindow testView;
    MainWindowViewModel vm;
    private Exception? initException;
    private bool xResult;
    private string sNewName = "NewName";
    private string sNewEmail = "NewEmail";
#pragma warning restore CS8618 // Ein Non-Nullable-Feld muss beim Beenden des Konstruktors einen Wert ungleich NULL enthalten. Erwägen Sie die Deklaration als Nullable.

    /// <summary>
    /// Initializes this instance.
    /// </summary>
    /// <autogeneratedoc />
    [TestInitialize]
    public void Init()
    {
        var t = new Thread(() => {
            try
            {
                testView = new();
                vm = (MainWindowViewModel)testView.DataContext;

                testView.NewDialogWindow = (o) =>
                {
                    var dw = Substitute.For<IDialogWindow>();
                    dw.DataContext.Returns(o);
                    dw.ShowDialog(Arg.Any<Avalonia.Controls.Window>()).Returns(_ =>
                    {
                        DoLog($"ShowDialog()=>{xResult}");
                        var dlgVm = (DialogWindowViewModel)dw.DataContext;
                        dlgVm.Name = sNewName;
                        dlgVm.Email = sNewEmail;
                        return Task.FromResult((xResult, (dlgVm.Name, dlgVm.Email)));
                    });
                    return dw;
                };

                var miWindowOpened = typeof(MainWindow).GetMethod("Window_Opened", BindingFlags.Instance | BindingFlags.NonPublic);
                Assert.IsNotNull(miWindowOpened);
                miWindowOpened!.Invoke(testView, new object?[] { this, EventArgs.Empty });
            }
            catch (Exception ex)
            {
                initException = ex;
            }
        });
        t.SetApartmentState(ApartmentState.STA); //Set the thread to STA
        t.Start();
        t.Join(); //Wait for the thread to end
        ClearLog();
    }

    [TestCleanup]
    public void Cleanup()
    {
        if (testView is not null)
            WeakReferenceMessenger.Default.UnregisterAll(testView);
    }

    private void EnsureInitialized()
    {
        if (initException is not null)
            Assert.Inconclusive($"Avalonia test environment unavailable: {initException.Message}");
    }

    /// <summary>
    /// Defines the test method MainWindowTest.
    /// </summary>
    /// <autogeneratedoc />
    [TestMethod()]
    public void MainWindowTest()
    {
        EnsureInitialized();
        Assert.IsNotNull(testView);
        Assert.IsInstanceOfType(testView, typeof(MainWindow));    
        Assert.IsNotNull(vm);
        Assert.IsInstanceOfType(vm, typeof(MainWindowViewModel));
        Assert.IsNotNull(vm.OpenDialogCommand);
        Assert.IsNotNull(vm.OpenMsgCommand);
    }


    [TestMethod]
    [DataRow("OKName", "OKMail", "OKName1", "OKMail1", true, new[] { "ShowDialog()=>True\r\n", "True", "OKName1", "OKMail1" })]
    [DataRow("NoName", "NoMail", "NoName1", "NoMail1", false, new[] { "ShowDialog()=>False\r\n", "False", "NoName1", "NoMail1" })]
    public async Task DoDialogWindowTest(string sAct1, string sAct2, string sAct3, string sAct4, bool xRes, string[] asExp)
    {
        EnsureInitialized();
        xResult = xRes;
        sNewName = sAct3;
        sNewEmail = sAct4;

        var request = new EditDialogRequestMessage(sAct1, sAct2);
        await WeakReferenceMessenger.Default.Send(request);
        var tRes = await request.Response;

        Assert.AreEqual(bool.Parse(asExp[1]), tRes.Item1);
        Assert.AreEqual(asExp[2], tRes.Item2.Item1);
        Assert.AreEqual(asExp[3], tRes.Item2.Item2);
        Assert.AreEqual(asExp[0], DebugLog);
    }
}
