<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\TranspilerLib.IEC\TranspilerLib.IEC.csproj" />
    <ProjectReference Include="..\..\..\TranspilerLib.IEC.Tests\TranspilerLib.IEC.Tests.csproj" />
  </ItemGroup>
</Project>
