// ***********************************************************************
// Assembly         : Calc64WF
// Author           : Mir
// Created          : 08-28-2022
//
// Last Modified By : Mir
// Last Modified On : 08-31-2022
// ***********************************************************************
// <copyright file="FrmCalc64MainViewModel.cs" company="JC-Soft">
//     Copyright © JC-Soft 2020
// </copyright>
// <summary></summary>
// ***********************************************************************
using BaseLib.Helper;
using Calc64Base.Models;
using Calc64Base.Models.Interfaces;
using Calc64WF.ViewModels.Interfaces;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MVVM.ViewModel;
using System;
using System.Runtime.Remoting.Channels;
using System.Windows.Forms;

namespace Calc64WF.ViewModel
{
    /// <summary>
    /// Class FrmCalc64MainViewModel.
    /// Implements the <see cref="BaseViewModel" />
    /// </summary>
    /// <seealso cref="BaseViewModel" />
    public partial class FrmCalc64MainViewModel : BaseViewModelCT, IFrmCalc64MainViewModel
    {
        #region Properties
        #region private properties
        /// <summary>
        /// The calc64model
        /// </summary>
        private ICalculator _calc64model;
        #endregion

        /// <summary>
        /// Occurs when [on data changed].
        /// </summary>
        public event EventHandler<(string prop, object? oldVal, object? newVal)> OnDataChanged;
        /// <summary>
        /// Occurs when [close form].
        /// </summary>
        public event EventHandler CloseForm;
        /// <summary>
        /// Occurs when [press number key].
        /// </summary>
        public event EventHandler<char> PressNumberKey;

        /// <summary>Gets or sets the accumulator.</summary>
        /// <value>The accumulator.</value>
        /// <autogeneratedoc />
        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(OperationCommand))]
        private long _accumulator;

        /// <summary>Gets or sets the memory.</summary>
        /// <value>The accumulator.</value>
        /// <autogeneratedoc />
        public long Memory { get => _calc64model.Memory; set => _calc64model.Memory = value; }

        /// <summary>Gets or sets the register.</summary>
        /// <value>The accumulator.</value>
        /// <autogeneratedoc />
        public long Register { get => _calc64model.Register; private set => _calc64model.Register = value; }

        /// <summary>Gets the operation text.</summary>
        /// <value>The accumulator.</value>
        /// <autogeneratedoc />
        public string OperationText { get => Calc64Model.GetShortDesc(_calc64model.OperationMode); }
        #endregion
        #region Methods
        /// <summary>
        /// Initializes a new instance of the <see cref="FrmCalc64MainViewModel"/> class.
        /// </summary>
        public FrmCalc64MainViewModel(ICalculator calculator)
        {
            _calc64model = calculator;
            _calc64model.CalcOperationChanged += model_CalcOpChanged;
            AddPropertyDependency(nameof(OperationText), nameof(_calc64model.OperationMode));
        }

        private void model_CalcOpChanged(object? s, (string prop, object? oldVal, object? newVal) e)
        {
            if (e.prop == nameof(Accumulator))
                Accumulator = (long)e.newVal;
            else
            {
                OnPropertyChanged(e.prop);
            }
            OnDataChanged?.Invoke(s, e);
        }

        /// <summary>
        /// BTNs the close click.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="tag">The tag.</param>
        /// <param name="e">The <see cref="EventArgs"/> instance containing the event data.</param>
        public void btnClose_Click(object sender, object tag, EventArgs e)
        {
            CloseForm?.Invoke(this, e);
        }

        private bool canDoNumber(object tag) => tag.AsInt() < 10;
        /// <summary>
        /// BTNs the nummber click.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="tag">The tag.</param>
        /// <param name="e">The <see cref="EventArgs"/> instance containing the event data.</param>
        [RelayCommand(CanExecute = nameof(canDoNumber))]
        private void @Number(object tag)
        {
            if (int.TryParse(tag.ToString(), out int aNumber))
            {
                _calc64model.Button(aNumber);
            }
        }

        private bool canDoOperation(object tag) => Accumulator != 0;
        /// <summary>
        /// BTNs the operator click.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="tag">The tag.</param>
        /// <param name="e">The <see cref="EventArgs"/> instance containing the event data.</param>
        [RelayCommand(CanExecute = nameof(canDoOperation))]
        private void Operation(object tag)
        {
            if (int.TryParse(tag.ToString(), out int aNumber))
            {
                _calc64model.Operation(-aNumber);
            }
        }

        /// <summary>
        /// BTNs the back click.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="tag">The tag.</param>
        /// <param name="e">The <see cref="EventArgs"/> instance containing the event data.</param>
        [RelayCommand]
        private void BackSpace(object tag)
            => _calc64model.BackSpace();

        /// <summary>
        /// FRMs the key down.
        /// </summary>
        /// <param name="sender">The sender.</param>
        /// <param name="tag">The tag.</param>
        /// <param name="e">The <see cref="KeyEventArgs"/> instance containing the event data.</param>
        public void frm_KeyDown(object sender, object tag, KeyEventArgs e)
        {
            Char ActKey = (char)0;
            if ((char)e.KeyValue >= "0"[0] && (char)e.KeyValue <= "9"[0])
            {
                ActKey = (char)e.KeyValue;
            }
            else if ((char)e.KeyValue >= 96 && (char)e.KeyValue <= 105)
            {
                ActKey = (char)(e.KeyValue - 96 + (int)("0"[0]));
            }

            switch (e.KeyCode)
            {
                case Keys.Oemplus:
                case Keys.Add:
                    Operation("-2");
                    break;
                case Keys.OemMinus:
                case Keys.Subtract:
                    Operation("-3");
                    break;
                case Keys.Divide:
                    //case Keys.Add:
                    Operation("-5");
                    break;
                case Keys.Multiply:
                    //case Keys.:
                    Operation("-4");
                    break;
                case Keys.Escape:
                    break;
                case Keys.Back:
                    BackSpace("");
                    break;
                default:
                    if (ActKey != (char)0)
                        @Number(ActKey);
                    break;
            }
        }

        #endregion
    }
}
