// ***********************************************************************
// Assembly         : MVVM_41_Sudoku_netTests
// Author           : Mir
// Created          : 05-14-2023
//
// Last Modified By : Mir
// Last Modified On : 05-14-2023
// ***********************************************************************
// <copyright file="SudokuViewModelTests.cs" company="JC-Soft">
//     Copyright © JC-Soft 2023
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.ComponentModel;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using NSubstitute;
using MVVM.ViewModel;
using MVVM.View.Extension;
using Sudoku_Base.Models.Interfaces;

/// <summary>
/// The Tests namespace.
/// </summary>
/// <autogeneratedoc />
namespace MVVM_41_Sudoku.ViewModels.Tests
{
    /// <summary>
    /// Defines test class SudokuViewModelTests.
    /// </summary>
    /// <autogeneratedoc />
    [TestClass()]
    public class SudokuViewModelTests : BaseTestViewModel<SudokuViewModel>
    {
        /// <summary>The model</summary>
        private ISudokuModel? _model;

        /// <summary>
        /// Initializes this instance.
        /// </summary>
        /// <autogeneratedoc />
        [TestInitialize]
        public override void Init()
        {
            IoC.GetReqSrv = (t) => t switch
            {
                Type _t when _t == typeof(ISudokuModel) => _model ??= Substitute.For<ISudokuModel>(),
                _ => throw new System.NotImplementedException($"No code for {t}")
            };
            base.Init();
        }

        /// <summary>
        /// Defines the test method SetupTest.
        /// </summary>
        /// <autogeneratedoc />
        [TestMethod()]
        public void SetupTest()
        {
            Assert.IsNotNull(testModel);
            Assert.IsInstanceOfType(testModel, typeof(SudokuViewModel));
            Assert.IsInstanceOfType(testModel, typeof(BaseViewModelCT));
            Assert.IsInstanceOfType(testModel, typeof(INotifyPropertyChanged));
            Assert.IsNotNull(_model);
        }

        [DataTestMethod()]
        [DataRow(nameof(ISudokuModel.Fields), new[] { "PropChg(MVVM_41_Sudoku.ViewModels.SudokuViewModel,Fields)=\r\n" })]
        [DataRow("HasErrors", new[] { "PropChg(MVVM_41_Sudoku.ViewModels.SudokuViewModel,HasErrors)=False\r\n" })]
        [DataRow("Dummy", new[] { "PropChg(MVVM_41_Sudoku.ViewModels.SudokuViewModel,Dummy)=\r\n" })]
        public void PropertyChangedTest(string prop, string[] asExp)
        {
            _model.PropertyChanged += Raise.Event<PropertyChangedEventHandler>(_model, new PropertyChangedEventArgs(prop));
            if (prop == nameof(ISudokuModel.Fields))
                _ = _model.Received(0).Fields;
            Assert.AreEqual(asExp[0], DebugLog);
        }
    }
}
