<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <Company>JC-Soft</Company>
    <Authors>JC-Soft</Authors>
    <RepositoryUrl>https://github.com/sarog/IDR</RepositoryUrl>
  </PropertyGroup>
</Project>
