0: Name:
0: Ref:
2: <A NAME="I12577">
4: </A>
3: Maria Magdalena  Reinmann 
0: info:
3: GEBURT
0: data:
4: </EM>
3: : 14 Jan 1786, Lahr, Baden, Germany\n
0: info:
3: TOD
0: data:
4: </EM>
3: : 11 Feb 1786, Lahr, Baden, Germany\n
0: info:
3: TAUFE
0: data:
4: </EM>
3: : 15 Jan 1786, Lahr, Baden, Germany\n
0: info:
3: BEGRÄBNIS
0: data:
4: </EM>
3: : 13 Feb 1786, Lahr, Baden, Germany\n
0: Eltern:
3: Vater: 
0: Ref:
2: <A HREF="../d0001/I8529.html">
3: Johann Gottlieb  Reinmann 
0: Eltern:
3: Mutter: 
0: Ref:
2: <A HREF="../d0000/I6962.html">
3: Maria Magdalena  Dorner 
