0: Name:
0: Ref:
2: <A NAME="I134">
4: </A>
3: Magdalena  Vieser 
0: info:
3: GEBURT
0: data:
4: </EM>
3: : 12 Aug 1693, Lahr, Baden, Germany\n
0: info:
3: TOD
0: data:
4: </EM>
3: : 31 Mar 1734, Lahr-Dinglingen, Baden, Germany\n
0: info:
3: VERWEIS
0: data:
4: </EM>
3: : Ic, 4\n
0: Eltern:
3: Vater: 
0: Ref:
2: <A HREF="../d0012/I105.html">
3: Hans Jakob  Vieser 
0: Eltern:
3: Mutter: 
0: Ref:
2: <A HREF="../d0012/I132.html">
3: Magdalena  Heckler 
0: Familie:
3: Familie 1
0: Partner:
0: Ref:
2: <A HREF="../d0004/I137.html">
3: Johann Peter  Volk 
0: info:
3: HEIRAT
0: data:
4: </EM>
3: : 16 Nov 1716, Lahr, Baden, Germany\n
0: Kind:
0: Ref:
2: <A HREF="../d0006/I3566.html">
3: Anna Maria  Volk 
0: Familie:
3: Familie 2
0: Partner:
0: Ref:
2: <A HREF="../d0000/I3674.html">
3: Michael  Voitländer 
0: info:
3: HEIRAT
0: data:
4: </EM>
3: : 29 Oct 1733, Lahr-Dinglingen, Baden, Germany\n
0: Kind:
0: Ref:
2: <A HREF="I3675.html">
3: Johann Jakob  Vieser 
