0: Name:
0: Ref:
2: <A NAME="I23">
4: </A>
3: Maria  Leser 
0: info:
3: TOD
0: data:
4: </EM>
3: : Lahr, Baden, Germany\n
0: info:
3: VERWEIS
0: data:
4: </EM>
3: : Ic, 2\n
0: Eltern:
3: Vater: 
0: Ref:
2: <A HREF="../d0002/I116.html">
3: Rudolf  Leser 
0: Eltern:
3: Mutter: 
0: Ref:
2: <A HREF="../d0003/I117.html">
3: Veronika  Geiger 
0: Familie:
3: Familie 1
0: Partner:
0: Ref:
2: <A HREF="../d0012/I22.html">
3: Georg  Vieser 
0: info:
3: HEIRAT
0: data:
4: </EM>
3: : ABT 1651, Lahr, Baden, Germany\n
0: Kind:
0: Ref:
2: <A HREF="../d0010/I20.html">
3: Hans  Vieser 
0: Kind:
0: Ref:
2: <A HREF="../d0012/I105.html">
3: Hans Jakob  Vieser 
0: Kind:
0: Ref:
2: <A HREF="I106.html">
3: Katharina  Vieser 
0: Kind:
0: Ref:
2: <A HREF="../d0001/I107.html">
3: Anna Barbara  Vieser 
